/**
 * Jit8j framework support by bruce yang 
 * contact email: 275060435@qq.com
 */
package dml.sz0099.course.app.module.define;

import org.jit4j.app.module.define.R;

/**
 * <pre>
 * @formatter:off
 *
 * 课程文章模块响应码
 * @author bruce yang at 2018-09-04 09:01:29
 * 
 * ----------------------------------------------------------------------------------------
 * Requirement		Author		Date		Function
 * init				bruceyang	2018-09-04	basic init
 * 
 * @formatter:on
 * </pre>
 */

public class CoeArticleRespCode extends CourseRespCode {


	// 定义模块名, 文章模块

	public static final String SZ0099_CODE_COURSE_ARTICLE_SUCCESS = R.initCode("300001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_SUCCESS = R.initMsg("文章操作成功", "SZ0099_MSG_COURSE_ARTICLE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_SUCCESS = R.initCode("300002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_SUCCESS = R.initMsg("您的订单已生成，请等待客服验证确认后发货", "SZ0099_MSG_COURSE_ARTICLE_ORDER_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_SUCCESS");


	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_NOT_EXIST = R.initCode("300003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_NOT_EXIST = R.initMsg("该订单不存在，参数错误", "SZ0099_MSG_COURSE_ARTICLE_ORDER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_NOT_LOGIN = R.initCode("300004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后下单", "SZ0099_MSG_COURSE_ARTICLE_ORDER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_USERID_CONFICT = R.initCode("300005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_USERID_CONFICT");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_USERID_CONFICT = R.initMsg("您预下单的身份与确认订单的身份不符，请使用相同帐号下单", "SZ0099_MSG_COURSE_ARTICLE_ORDER_USERID_CONFICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_USERID_CONFICT");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_PAYED = R.initCode("300006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_PAYED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_PAYED = R.initMsg("您的订单已经执行过支付操作了，请确认微信钱包或支付宝交易流水是否已打款", "SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_PAYED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_PAYED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_SENT = R.initCode("300007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_SENT");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_SENT = R.initMsg("您的订单已发货，请注意查收", "SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_SENT");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_RECIEVED = R.initCode("300008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_RECIEVED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_RECIEVED = R.initMsg("您的订单已签收", "SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_RECIEVED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_RECIEVED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_TM_RECIEVED = R.initCode("300009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_TM_RECIEVED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_TM_RECIEVED = R.initMsg("您的订单已超时签收", "SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_TM_RECIEVED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_TM_RECIEVED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_INPROCESS = R.initCode("300010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_INPROCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_INPROCESS = R.initMsg("您的订单已被客服处理中，敬请等待一下", "SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_INPROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_INPROCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_BUY_INSTRUCTION_SUCCESS = R.initCode("300011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_INSTRUCTION_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_BUY_INSTRUCTION_SUCCESS = R.initMsg("购买说明查看成功", "SZ0099_MSG_COURSE_ARTICLE_BUY_INSTRUCTION_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_INSTRUCTION_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_FLOWERID_SUCCESS = R.initCode("300012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_FLOWERID_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_FLOWERID_SUCCESS = R.initMsg("订单流水号生成成功", "SZ0099_MSG_COURSE_ARTICLE_ORDER_FLOWERID_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_FLOWERID_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_INVALID_USERID = R.initCode("300013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_INVALID_USERID");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_INVALID_USERID = R.initMsg("订单身份不合法", "SZ0099_MSG_COURSE_ARTICLE_ORDER_INVALID_USERID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_INVALID_USERID");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_NO_SENT = R.initCode("300014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NO_SENT");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_NO_SENT = R.initMsg("该订单尚未被客服审核确认，请确保您已付款成功并在支付时“添加备注”填写了订单流水号，如急需提取，请联系客服人员确认有效。", "SZ0099_MSG_COURSE_ARTICLE_ORDER_NO_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NO_SENT");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_EXPIRED = R.initCode("300015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_EXPIRED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_EXPIRED = R.initMsg("该订单已过期，提取码已失效，如需服务请重新下单。", "SZ0099_MSG_COURSE_ARTICLE_ORDER_EXPIRED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_EXPIRED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_CLOSED = R.initCode("300016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_CLOSED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_CLOSED = R.initMsg("订单已被关闭", "SZ0099_MSG_COURSE_ARTICLE_ORDER_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_CLOSED");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_CANCEL = R.initCode("300017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_CANCEL");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_CANCEL = R.initMsg("订单已被取消", "SZ0099_MSG_COURSE_ARTICLE_ORDER_CANCEL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_CANCEL");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_QUERY_PULLCODE_PASSED = R.initCode("300018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_QUERY_PULLCODE_PASSED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_QUERY_PULLCODE_PASSED = R.initMsg("订单校验通过，可以查看", "SZ0099_MSG_COURSE_ARTICLE_ORDER_QUERY_PULLCODE_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_QUERY_PULLCODE_PASSED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_NULL_EXPIRED = R.initCode("300019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NULL_EXPIRED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_NULL_EXPIRED = R.initMsg("数据非法，该订单过期时间未设定", "SZ0099_MSG_COURSE_ARTICLE_ORDER_NULL_EXPIRED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_NULL_EXPIRED");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_SENT = R.initCode("300020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_SENT");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_SENT = R.initMsg("订单已发货，不能修改", "SZ0099_MSG_COURSE_ARTICLE_ORDER_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_SENT");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_FINISHED = R.initCode("300021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_FINISHED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_FINISHED = R.initMsg("订单已结束", "SZ0099_MSG_COURSE_ARTICLE_ORDER_FINISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_FINISHED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_PASSED = R.initCode("300022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_PASSED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_PASSED = R.initMsg("订单校验通过，可以修改", "SZ0099_MSG_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_PASSED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_SUCCESS = R.initCode("300023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_SUCCESS = R.initMsg("订单Email修改成功", "SZ0099_MSG_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_MODIFY_EMAIL_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_IN_PROCESS = R.initCode("300024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_IN_PROCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_IN_PROCESS = R.initMsg("订单已被处理过", "SZ0099_MSG_COURSE_ARTICLE_ORDER_HAS_IN_PROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_HAS_IN_PROCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_INPROCESS_SUCCESS = R.initCode("300025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_INPROCESS_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_INPROCESS_SUCCESS = R.initMsg("订单已加入处理中", "SZ0099_MSG_COURSE_ARTICLE_ORDER_INPROCESS_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_INPROCESS_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_ORDER_SENT_SUCCESS = R.initCode("300026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_SENT_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_ORDER_SENT_SUCCESS = R.initMsg("订单已发货", "SZ0099_MSG_COURSE_ARTICLE_ORDER_SENT_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_ORDER_SENT_SUCCESS");

	
	
	
	
	
	
	
	
	public static final String SZ0099_CODE_COURSE_ARTICLE_NOT_EXIST = R.initCode("310000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_ARTICLE_NOT_EXIST = R.initMsg("您要查询的文章不存在", "SZ0099_MSG_COURSE_ARTICLE_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_ARTICLE_SHELVED_NO = R.initCode("310001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_SHELVED_NO");
	public static final String SZ0099_MSG_COURSE_ARTICLE_SHELVED_NO = R.initMsg("您要查询的文章已被下架", "SZ0099_MSG_COURSE_ARTICLE_SHELVED_NO", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_SHELVED_NO");

	public static final String SZ0099_CODE_COURSE_ARTICLE_HAS_DELTETED = R.initCode("310002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_HAS_DELTETED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_HAS_DELTETED = R.initMsg("您要查询的文章已被删除", "SZ0099_MSG_COURSE_ARTICLE_HAS_DELTETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_HAS_DELTETED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_DRAFT_EXTRA = R.initCode("310003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_DRAFT_EXTRA");
	public static final String SZ0099_MSG_COURSE_ARTICLE_DRAFT_EXTRA = R.initMsg("先完成以下草稿吧", "SZ0099_MSG_COURSE_ARTICLE_DRAFT_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_DRAFT_EXTRA");

	public static final String SZ0099_CODE_COURSE_ARTICLE_NAME_EMPTY = R.initCode("310004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_NAME_EMPTY = R.initMsg("文章名称不能为空", "SZ0099_MSG_COURSE_ARTICLE_NAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NAME_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_NAME_EXTRA_LENGTH = R.initCode("310005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NAME_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_ARTICLE_NAME_EXTRA_LENGTH = R.initMsg("文章名称字符数超长", "SZ0099_MSG_COURSE_ARTICLE_NAME_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NAME_EXTRA_LENGTH");

	public static final String SZ0099_CODE_COURSE_ARTICLE_TITLE_EMPTY = R.initCode("310006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_TITLE_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_TITLE_EMPTY = R.initMsg("文章标题不能为空", "SZ0099_MSG_COURSE_ARTICLE_TITLE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_TITLE_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_TITLE_EXTRA_LENGTH = R.initCode("310007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_TITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_ARTICLE_TITLE_EXTRA_LENGTH = R.initMsg("文章标题字符数超长", "SZ0099_MSG_COURSE_ARTICLE_TITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_TITLE_EXTRA_LENGTH");

	public static final String SZ0099_CODE_COURSE_ARTICLE_DESCRIPTION_EMPTY = R.initCode("310008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_DESCRIPTION_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_DESCRIPTION_EMPTY = R.initMsg("文章描述不能为空", "SZ0099_MSG_COURSE_ARTICLE_DESCRIPTION_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_DESCRIPTION_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_DESCRIPTION_EXTRA_LENGTH = R.initCode("310009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_DESCRIPTION_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_ARTICLE_DESCRIPTION_EXTRA_LENGTH = R.initMsg("文章描述字符数超长", "SZ0099_MSG_COURSE_ARTICLE_DESCRIPTION_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_DESCRIPTION_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_BASEINFO_SUCCESS = R.initCode("310010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_BASEINFO_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_BASEINFO_SUCCESS = R.initMsg("更新文章基本信息成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_BASEINFO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_BASEINFO_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_BUY_NOT_EXIST = R.initCode("310011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_ARTICLE_BUY_NOT_EXIST = R.initMsg("您要购买的文章不存在", "SZ0099_MSG_COURSE_ARTICLE_BUY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_ARTICLE_BUY_SHELVED_NO = R.initCode("310012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_SHELVED_NO");
	public static final String SZ0099_MSG_COURSE_ARTICLE_BUY_SHELVED_NO = R.initMsg("您要购买的文章已被下架", "SZ0099_MSG_COURSE_ARTICLE_BUY_SHELVED_NO", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_SHELVED_NO");

	public static final String SZ0099_CODE_COURSE_ARTICLE_BUY_HAS_DELTETED = R.initCode("310013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_HAS_DELTETED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_BUY_HAS_DELTETED = R.initMsg("您要购买的文章已被删除", "SZ0099_MSG_COURSE_ARTICLE_BUY_HAS_DELTETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_HAS_DELTETED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_BUY_USER_SELF = R.initCode("310014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_USER_SELF");
	public static final String SZ0099_MSG_COURSE_ARTICLE_BUY_USER_SELF = R.initMsg("您不能购买自己发布的文章", "SZ0099_MSG_COURSE_ARTICLE_BUY_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_BUY_USER_SELF");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_NOT_USER_SELF = R.initCode("310015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NOT_USER_SELF");
	public static final String SZ0099_MSG_COURSE_ARTICLE_NOT_USER_SELF = R.initMsg("您无权修改不是自己的文章", "SZ0099_MSG_COURSE_ARTICLE_NOT_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NOT_USER_SELF");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_UNPUBLISHED_SUCCESS = R.initCode("310016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_UNPUBLISHED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_UNPUBLISHED_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_UNPUBLISHED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_UNPUBLISHED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_REFRESH_INVALID = R.initCode("310017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_REFRESH_INVALID");
	public static final String SZ0099_MSG_COURSE_ARTICLE_REFRESH_INVALID = R.initMsg("未超过有效期，不能刷新", "SZ0099_MSG_COURSE_ARTICLE_REFRESH_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_REFRESH_INVALID");

	public static final String SZ0099_CODE_COURSE_ARTICLE_REFRESH_EXTRA = R.initCode("310018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_REFRESH_EXTRA");
	public static final String SZ0099_MSG_COURSE_ARTICLE_REFRESH_EXTRA = R.initMsg("超过365天的文章，不再支持刷新", "SZ0099_MSG_COURSE_ARTICLE_REFRESH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_REFRESH_EXTRA");

	public static final String SZ0099_CODE_COURSE_ARTICLE_REFRESH_SUCCESS = R.initCode("310019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_REFRESH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_REFRESH_SUCCESS = R.initMsg("刷新成功", "SZ0099_MSG_COURSE_ARTICLE_REFRESH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_REFRESH_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_PRICEORI_EMPTY = R.initCode("310020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRICEORI_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PRICEORI_EMPTY = R.initMsg("文章原价不能为空", "SZ0099_MSG_COURSE_ARTICLE_PRICEORI_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRICEORI_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PRICECUR_EMPTY = R.initCode("310021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRICECUR_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PRICECUR_EMPTY = R.initMsg("文章现价不能为空", "SZ0099_MSG_COURSE_ARTICLE_PRICECUR_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRICECUR_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_STRATEGY_EMPTY = R.initCode("310022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_STRATEGY_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_STRATEGY_EMPTY = R.initMsg("文章优惠策略不能为空", "SZ0099_MSG_COURSE_ARTICLE_STRATEGY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_STRATEGY_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_GRADE_EMPTY = R.initCode("310023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_GRADE_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_GRADE_EMPTY = R.initMsg("文章等级不能为空", "SZ0099_MSG_COURSE_ARTICLE_GRADE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_GRADE_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_RATES_EMPTY = R.initCode("310024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_RATES_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_RATES_EMPTY = R.initMsg("文章最低优惠折扣不能为空", "SZ0099_MSG_COURSE_ARTICLE_RATES_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_RATES_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_RATES_EXTRA = R.initCode("310025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_RATES_EXTRA");
	public static final String SZ0099_MSG_COURSE_ARTICLE_RATES_EXTRA = R.initMsg("文章最低优惠折扣超出设置范围", "SZ0099_MSG_COURSE_ARTICLE_RATES_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_RATES_EXTRA");

	public static final String SZ0099_CODE_COURSE_ARTICLE_GRADE_MORETHAN_9 = R.initCode("310026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_GRADE_MORETHAN_9");
	public static final String SZ0099_MSG_COURSE_ARTICLE_GRADE_MORETHAN_9 = R.initMsg("文章等级大于9时，请与管理员联系", "SZ0099_MSG_COURSE_ARTICLE_GRADE_MORETHAN_9", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_GRADE_MORETHAN_9");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PULL_METHOD_EMPTY = R.initCode("310027", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_METHOD_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PULL_METHOD_EMPTY = R.initMsg("文章提取方式不能为空", "SZ0099_MSG_COURSE_ARTICLE_PULL_METHOD_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_METHOD_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_LINK_EMPTY = R.initCode("310028", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_LINK_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_LINK_EMPTY = R.initMsg("文章链接不能为空", "SZ0099_MSG_COURSE_ARTICLE_LINK_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_LINK_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_EMPTY = R.initCode("310029", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PULL_CODE_EMPTY = R.initMsg("文章提取密码不能为空", "SZ0099_MSG_COURSE_ARTICLE_PULL_CODE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_USER_NOT_LOGIN = R.initCode("300030", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_ARTICLE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后修改", "SZ0099_MSG_COURSE_ARTICLE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_TITLE_SUCCESS = R.initCode("310031", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PRICE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_TITLE_SUCCESS = R.initMsg("更新文章标题成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_PRICE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PRICE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_DESCRPTION_SUCCESS = R.initCode("310069", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PRICE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_DESCRPTION_SUCCESS = R.initMsg("更新文章概要成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_PRICE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PRICE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_LENGTH_LESS_4 = R.initCode("310032", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_LENGTH_LESS_4");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PULL_CODE_LENGTH_LESS_4 = R.initMsg("文章提取密码长度不能小于4位", "SZ0099_MSG_COURSE_ARTICLE_PULL_CODE_LENGTH_LESS_4", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_LENGTH_LESS_4");

	public static final String SZ0099_CODE_COURSE_ARTICLE_LINK_LENGTH_MORE_LONG = R.initCode("310033", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_LINK_LENGTH_MORE_LONG");
	public static final String SZ0099_MSG_COURSE_ARTICLE_LINK_LENGTH_MORE_LONG = R.initMsg("下载链接太长了", "SZ0099_MSG_COURSE_ARTICLE_LINK_LENGTH_MORE_LONG", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_LINK_LENGTH_MORE_LONG");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_LENGTH_TOO_LONG = R.initCode("310034", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_LENGTH_TOO_LONG");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PULL_CODE_LENGTH_TOO_LONG = R.initMsg("文章提取密码长度不能大于10位", "SZ0099_MSG_COURSE_ARTICLE_PULL_CODE_LENGTH_TOO_LONG", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PULL_CODE_LENGTH_TOO_LONG");

	public static final String SZ0099_CODE_COURSE_ARTICLE_EDIT_QUICKLY_SUCCESS = R.initCode("310035", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_EDIT_QUICKLY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_EDIT_QUICKLY_SUCCESS = R.initMsg("快速编辑保存成功", "SZ0099_MSG_COURSE_ARTICLE_EDIT_QUICKLY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_EDIT_QUICKLY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_PUBLISH_SUCCESS = R.initCode("310036", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PUBLISH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_PUBLISH_SUCCESS = R.initMsg("文章发布成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_PUBLISH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PUBLISH_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_PUBLISHED = R.initCode("310037", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_PUBLISHED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_HAS_PUBLISHED = R.initMsg("文章已发布", "SZ0099_MSG_COURSE_ARTICLE_MERGE_HAS_PUBLISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_PUBLISHED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_CLOSED = R.initCode("310038", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_CLOSED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_HAS_CLOSED = R.initMsg("文章已关闭，若要开启请联系管理员！", "SZ0099_MSG_COURSE_ARTICLE_MERGE_HAS_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_CLOSED");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_CLOSED_SUCCESS = R.initCode("310039", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_CLOSED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_CLOSED_SUCCESS = R.initMsg("文章关闭成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_CLOSED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_CLOSED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_NOT_PUBLISH = R.initCode("310040", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NOT_PUBLISH");
	public static final String SZ0099_MSG_COURSE_ARTICLE_NOT_PUBLISH = R.initMsg("文章尚未发布", "SZ0099_MSG_COURSE_ARTICLE_NOT_PUBLISH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_NOT_PUBLISH");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ARTICLE_USERID_NULL = R.initCode("310041", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ARTICLE_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ARTICLE_USERID_NULL = R.initMsg("文章用户id为空，非法文章，禁止编辑", "SZ0099_MSG_COURSE_PARAGRAGH_ARTICLE_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ARTICLE_USERID_NULL");
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL = R.initCode("310042", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_USERID_NULL = R.initMsg("还没登录，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT = R.initCode("310043", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_USERID_CONFLICT = R.initMsg("非本人发布的文章，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_USERID_CONFLICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA = R.initCode("310044", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_TOTAL_EXTRA = R.initMsg("段落总数超限，请减少后再增加", "SZ0099_MSG_COURSE_PARAGRAGH_TOTAL_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST = R.initCode("310045", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_NOT_EXIST = R.initMsg("段落不存在", "SZ0099_MSG_COURSE_PARAGRAGH_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST");

	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS = R.initCode("310046", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_MERGE_SUCCESS = R.initMsg("段落保存成功", "SZ0099_MSG_COURSE_PARAGRAGH_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST = R.initCode("310046", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST = R.initMsg("段落上传数据不存在", "SZ0099_MSG_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS = R.initCode("310047", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_DELETE_SUCCESS = R.initMsg("段落删除成功", "SZ0099_MSG_COURSE_PARAGRAGH_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS = R.initCode("310048", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ADD_SUCCESS = R.initMsg("段落添加成功", "SZ0099_MSG_COURSE_PARAGRAGH_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS = R.initCode("310049", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS = R.initMsg("已全部删除，成功", "SZ0099_MSG_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_SUBTITLE_EXTRA_LENGTH = R.initCode("310050", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_SUBTITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_ARTICLE_SUBTITLE_EXTRA_LENGTH = R.initMsg("文章子标题字符数超长", "SZ0099_MSG_COURSE_ARTICLE_SUBTITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_SUBTITLE_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_DELERED_SUCCESS = R.initCode("310058", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_DELERED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_DELERED_SUCCESS = R.initMsg("文章删除成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_DELERED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_DELERED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_PRAISE_SUCCESS = R.initCode("310059", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PRAISE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_PRAISE_SUCCESS = R.initMsg("文章点赞成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_PRAISE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_PRAISE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PRAISE_USER_NOT_LOGIN = R.initCode("310060", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRAISE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PRAISE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后点赞", "SZ0099_MSG_COURSE_ARTICLE_PRAISE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRAISE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PRAISE_EXIST = R.initCode("310061", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRAISE_EXIST");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PRAISE_EXIST = R.initMsg("你已经点过赞了", "SZ0099_MSG_COURSE_ARTICLE_PRAISE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRAISE_EXIST");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PRAISE_USER_SELF_NOALLOW = R.initCode("310062", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRAISE_USER_SELF_NOALLOW");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PRAISE_USER_SELF_NOALLOW = R.initMsg("自己赞自己？还是让别人来点赞吧！", "SZ0099_MSG_COURSE_ARTICLE_PRAISE_USER_SELF_NOALLOW", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PRAISE_USER_SELF_NOALLOW");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_FAVIRATE_SUCCESS = R.initCode("310063", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_FAVIRATE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_FAVIRATE_SUCCESS = R.initMsg("文章收藏成功", "SZ0099_MSG_COURSE_ARTICLE_MERGE_FAVIRATE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_FAVIRATE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_USER_NOT_LOGIN = R.initCode("310064", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_ARTICLE_FAVIRATE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后点赞", "SZ0099_MSG_COURSE_ARTICLE_FAVIRATE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_EXIST = R.initCode("310065", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_EXIST");
	public static final String SZ0099_MSG_COURSE_ARTICLE_FAVIRATE_EXIST = R.initMsg("你已经收藏过了", "SZ0099_MSG_COURSE_ARTICLE_FAVIRATE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_EXIST");

	public static final String SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_USER_SELF_NOALLOW = R.initCode("310066", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_USER_SELF_NOALLOW");
	public static final String SZ0099_MSG_COURSE_ARTICLE_FAVIRATE_USER_SELF_NOALLOW = R.initMsg("自己的也收藏？让别人收藏吧！", "SZ0099_MSG_COURSE_ARTICLE_FAVIRATE_USER_SELF_NOALLOW", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_FAVIRATE_USER_SELF_NOALLOW");

	public static final String SZ0099_CODE_COURSE_ARTICLE_CATEGORY_EMPTY = R.initCode("310067", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_CATEGORY_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLE_CATEGORY_EMPTY = R.initMsg("文章还没选择分类", "SZ0099_MSG_COURSE_ARTICLE_CATEGORY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_CATEGORY_EMPTY");

	public static final String SZ0099_CODE_COURSE_ARTICLE_PUBLISHED_NO_COVER = R.initCode("310068", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PUBLISHED_NO_COVER");
	public static final String SZ0099_MSG_COURSE_ARTICLE_PUBLISHED_NO_COVER = R.initMsg("没有上传封面图", "SZ0099_MSG_COURSE_ARTICLE_PUBLISHED_NO_COVER", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_PUBLISHED_NO_COVER");

	
	
	
	public static final String SZ0099_CODE_COURSE_ARTICLEID_EMPTY = R.initCode("311005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_ARTICLEID_EMPTY = R.initMsg("添加标签时，文章ID不能为空", "SZ0099_MSG_COURSE_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLEID_EMPTY");

	public static final String SZ0099_CODE_COURSE_DELETE_ARTICLEID_EMPTY = R.initCode("311009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_DELETE_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_DELETE_ARTICLEID_EMPTY = R.initMsg("删除标签时，文章ID不能为空", "SZ0099_MSG_COURSE_DELETE_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_DELETE_ARTICLEID_EMPTY");

	
	//------------------------------
	
	
	
	
	public static final String SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_SUCCESS = R.initCode("312100", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_SUCCESS");
	public static final String SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_SUCCESS");

	public static final String SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_EMPLTY = R.initCode("312106", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_EMPLTY = R.initMsg("用户id为空，请登录再试", "SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_EMPLTY = R.initCode("312101", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_EMPLTY = R.initMsg("此操作id不能为空", "SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY = R.initCode("312102", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY");
	public static final String SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY = R.initMsg("查无此实体", "SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY");

	public static final String SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_INVALID = R.initCode("312103", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_INVALID");
	public static final String SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_INVALID = R.initMsg("非法操作用户", "SZ0099_MSG_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PARAGRAGH_PHOTO_USERID_INVALID");

	
	public static final String SZ0099_CODE_OOD_ARTICLE_PHOTO_MAINID_EMPLTY = R.initCode("312104", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PHOTO_MAINID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ARTICLE_PHOTO_MAINID_EMPLTY = R.initMsg("所绑定的文章ID为空", "SZ0099_MSG_OOD_ARTICLE_PHOTO_MAINID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PHOTO_MAINID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ARTICLE_PHOTO_MAINNUM_EXTRA = R.initCode("312105", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PHOTO_MAINNUM_EXTRA");
	public static final String SZ0099_MSG_OOD_ARTICLE_PHOTO_MAINNUM_EXTRA = R.initMsg("图片数量超限", "SZ0099_MSG_OOD_ARTICLE_PHOTO_MAINNUM_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ARTICLE_PHOTO_MAINNUM_EXTRA");

	
	
	
	
	
	
	
	//------------------
	
	
	public static final String SZ0099_CODE_COURSE_PERSONAL_ARTICLE_EXTRA = R.initCode("330003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ARTICLE_EXTRA");
	public static final String SZ0099_MSG_COURSE_PERSONAL_ARTICLE_EXTRA = R.initMsg("文章数已经满了", "SZ0099_MSG_COURSE_PERSONAL_ARTICLE_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ARTICLE_EXTRA");

	public static final String SZ0099_CODE_COURSE_PERSONAL_ARTICLE_NOT_EXIST = R.initCode("330004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ARTICLE_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PERSONAL_ARTICLE_NOT_EXIST = R.initMsg("您要查询的文章不存在", "SZ0099_MSG_COURSE_PERSONAL_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ARTICLE_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_ARTICLE_USERID_NULL = R.initCode("330005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_ARTICLE_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_PERSONAL_ARTICLE_USERID_NULL = R.initMsg("用户id为空，非法文章，禁止修炼", "SZ0099_MSG_COURSE_PARAGRAGH_PERSONAL_ARTICLE_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_ARTICLE_USERID_NULL");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ARTICLE_USERID_CONFLICT = R.initCode("330006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ARTICLE_USERID_CONFLICT");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ARTICLE_USERID_CONFLICT = R.initMsg("非本人文章，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_ARTICLE_USERID_CONFLICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ARTICLE_USERID_CONFLICT");

	public static final String SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_DELERED = R.initCode("330007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_DELERED");
	public static final String SZ0099_MSG_COURSE_ARTICLE_MERGE_HAS_DELERED = R.initMsg("文章已被删除！", "SZ0099_MSG_COURSE_ARTICLE_MERGE_HAS_DELERED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_MERGE_HAS_DELERED");


	public static final String SZ0099_CODE_COURSE_TAG_ARTICLEID_EMPTY = R.initCode("331005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_ARTICLEID_EMPTY = R.initMsg("添加标签时，文章ID不能为空", "SZ0099_MSG_COURSE_TAG_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ARTICLEID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_DELETE_ARTICLEID_EMPTY = R.initCode("331009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_DELETE_ARTICLEID_EMPTY = R.initMsg("删除标签时，文章ID不能为空", "SZ0099_MSG_COURSE_TAG_DELETE_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_ARTICLEID_EMPTY");

}
