/**
 * Jit8j framework support by bruce yang 
 * contact email: 275060435@qq.com
 */
package dml.sz0099.course.app.module.define;

import org.jit4j.app.module.define.R;

/**
 * <pre>
 * @formatter:off
 *
 * 课程活动模块响应码
 * @author bruce yang at 2018-09-04 09:01:29
 * 
 * ----------------------------------------------------------------------------------------
 * Requirement		Author		Date		Function
 * init				bruceyang	2018-09-04	basic init
 * 
 * @formatter:on
 * </pre>
 */

public class CoeActivityRespCode extends CourseRespCode {


	// 定义模块名, 活动模块

	public static final String SZ0099_CODE_OOD_ACTIVITY_SUCCESS = R.initCode("500001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_SUCCESS = R.initMsg("活动操作成功", "SZ0099_MSG_OOD_ACTIVITY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_SUCCESS");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_SUCCESS = R.initCode("500002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_SUCCESS = R.initMsg("您的订单已生成，请等待客服验证确认后发货", "SZ0099_MSG_OOD_ACTIVITY_ORDER_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_SUCCESS");


	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_NOT_EXIST = R.initCode("500003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_NOT_EXIST = R.initMsg("该订单不存在，参数错误", "SZ0099_MSG_OOD_ACTIVITY_ORDER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_NOT_LOGIN = R.initCode("500004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NOT_LOGIN");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后下单", "SZ0099_MSG_OOD_ACTIVITY_ORDER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NOT_LOGIN");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_USERID_CONFICT = R.initCode("500005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_USERID_CONFICT");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_USERID_CONFICT = R.initMsg("您预下单的身份与确认订单的身份不符，请使用相同帐号下单", "SZ0099_MSG_OOD_ACTIVITY_ORDER_USERID_CONFICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_USERID_CONFICT");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_PAYED = R.initCode("500006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_PAYED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_PAYED = R.initMsg("您的订单已经执行过支付操作了，请确认微信钱包或支付宝交易流水是否已打款", "SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_PAYED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_PAYED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_SENT = R.initCode("500007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_SENT");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_SENT = R.initMsg("您的订单已发货，请注意查收", "SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_SENT");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_RECIEVED = R.initCode("500008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_RECIEVED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_RECIEVED = R.initMsg("您的订单已签收", "SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_RECIEVED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_RECIEVED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_TM_RECIEVED = R.initCode("500009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_TM_RECIEVED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_TM_RECIEVED = R.initMsg("您的订单已超时签收", "SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_TM_RECIEVED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_TM_RECIEVED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_INPROCESS = R.initCode("500010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_INPROCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_INPROCESS = R.initMsg("您的订单已被客服处理中，敬请等待一下", "SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_INPROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_INPROCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_BUY_INSTRUCTION_SUCCESS = R.initCode("500011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_INSTRUCTION_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_BUY_INSTRUCTION_SUCCESS = R.initMsg("购买说明查看成功", "SZ0099_MSG_OOD_ACTIVITY_BUY_INSTRUCTION_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_INSTRUCTION_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_FLOWERID_SUCCESS = R.initCode("500012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_FLOWERID_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_FLOWERID_SUCCESS = R.initMsg("订单流水号生成成功", "SZ0099_MSG_OOD_ACTIVITY_ORDER_FLOWERID_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_FLOWERID_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_INVALID_USERID = R.initCode("500013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_INVALID_USERID");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_INVALID_USERID = R.initMsg("订单身份不合法", "SZ0099_MSG_OOD_ACTIVITY_ORDER_INVALID_USERID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_INVALID_USERID");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_NO_SENT = R.initCode("500014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NO_SENT");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_NO_SENT = R.initMsg("该订单尚未被客服审核确认，请确保您已付款成功并在支付时“添加备注”填写了订单流水号，如急需提取，请联系客服人员确认有效。", "SZ0099_MSG_OOD_ACTIVITY_ORDER_NO_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NO_SENT");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_EXPIRED = R.initCode("500015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_EXPIRED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_EXPIRED = R.initMsg("该订单已过期，提取码已失效，如需服务请重新下单。", "SZ0099_MSG_OOD_ACTIVITY_ORDER_EXPIRED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_EXPIRED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_CLOSED = R.initCode("500016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_CLOSED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_CLOSED = R.initMsg("订单已被关闭", "SZ0099_MSG_OOD_ACTIVITY_ORDER_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_CLOSED");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_CANCEL = R.initCode("500017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_CANCEL");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_CANCEL = R.initMsg("订单已被取消", "SZ0099_MSG_OOD_ACTIVITY_ORDER_CANCEL", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_CANCEL");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_QUERY_PULLCODE_PASSED = R.initCode("500018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_QUERY_PULLCODE_PASSED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_QUERY_PULLCODE_PASSED = R.initMsg("订单校验通过，可以查看", "SZ0099_MSG_OOD_ACTIVITY_ORDER_QUERY_PULLCODE_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_QUERY_PULLCODE_PASSED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_NULL_EXPIRED = R.initCode("500019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NULL_EXPIRED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_NULL_EXPIRED = R.initMsg("数据非法，该订单过期时间未设定", "SZ0099_MSG_OOD_ACTIVITY_ORDER_NULL_EXPIRED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_NULL_EXPIRED");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_SENT = R.initCode("500020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_SENT");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_SENT = R.initMsg("订单已发货，不能修改", "SZ0099_MSG_OOD_ACTIVITY_ORDER_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_SENT");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_FINISHED = R.initCode("500021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_FINISHED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_FINISHED = R.initMsg("订单已结束", "SZ0099_MSG_OOD_ACTIVITY_ORDER_FINISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_FINISHED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_PASSED = R.initCode("500022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_PASSED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_PASSED = R.initMsg("订单校验通过，可以修改", "SZ0099_MSG_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_PASSED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_SUCCESS = R.initCode("500023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_SUCCESS = R.initMsg("订单Email修改成功", "SZ0099_MSG_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_MODIFY_EMAIL_SUCCESS");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_IN_PROCESS = R.initCode("500024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_IN_PROCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_IN_PROCESS = R.initMsg("订单已被处理过", "SZ0099_MSG_OOD_ACTIVITY_ORDER_HAS_IN_PROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_HAS_IN_PROCESS");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_INPROCESS_SUCCESS = R.initCode("500025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_INPROCESS_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_INPROCESS_SUCCESS = R.initMsg("订单已加入处理中", "SZ0099_MSG_OOD_ACTIVITY_ORDER_INPROCESS_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_INPROCESS_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORDER_SENT_SUCCESS = R.initCode("500026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_SENT_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORDER_SENT_SUCCESS = R.initMsg("订单已发货", "SZ0099_MSG_OOD_ACTIVITY_ORDER_SENT_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORDER_SENT_SUCCESS");

	
	
	
	
	
	
	
	
	public static final String SZ0099_CODE_OOD_ACTIVITY_NOT_EXIST = R.initCode("510000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACTIVITY_NOT_EXIST = R.initMsg("您要查询的活动不存在", "SZ0099_MSG_OOD_ACTIVITY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACTIVITY_SHELVED_NO = R.initCode("510001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_SHELVED_NO");
	public static final String SZ0099_MSG_OOD_ACTIVITY_SHELVED_NO = R.initMsg("您要查询的活动已被下架", "SZ0099_MSG_OOD_ACTIVITY_SHELVED_NO", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_SHELVED_NO");

	public static final String SZ0099_CODE_OOD_ACTIVITY_HAS_DELTETED = R.initCode("510002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_HAS_DELTETED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_HAS_DELTETED = R.initMsg("您要查询的活动已被删除", "SZ0099_MSG_OOD_ACTIVITY_HAS_DELTETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_HAS_DELTETED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_DRAFT_EXTRA = R.initCode("510003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DRAFT_EXTRA");
	public static final String SZ0099_MSG_OOD_ACTIVITY_DRAFT_EXTRA = R.initMsg("先完成以下草稿吧", "SZ0099_MSG_OOD_ACTIVITY_DRAFT_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DRAFT_EXTRA");

	public static final String SZ0099_CODE_OOD_ACTIVITY_NAME_EMPTY = R.initCode("510004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NAME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_NAME_EMPTY = R.initMsg("活动名称不能为空", "SZ0099_MSG_OOD_ACTIVITY_NAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NAME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_NAME_EXTRA_LENGTH = R.initCode("510005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NAME_EXTRA_LENGTH");
	public static final String SZ0099_MSG_OOD_ACTIVITY_NAME_EXTRA_LENGTH = R.initMsg("活动名称字符数超长", "SZ0099_MSG_OOD_ACTIVITY_NAME_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NAME_EXTRA_LENGTH");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TITLE_EMPTY = R.initCode("510006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TITLE_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TITLE_EMPTY = R.initMsg("活动标题不能为空", "SZ0099_MSG_OOD_ACTIVITY_TITLE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TITLE_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TITLE_EXTRA_LENGTH = R.initCode("510007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TITLE_EXTRA_LENGTH = R.initMsg("活动标题字符数超长", "SZ0099_MSG_OOD_ACTIVITY_TITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TITLE_EXTRA_LENGTH");

	public static final String SZ0099_CODE_OOD_ACTIVITY_DESCRIPTION_EMPTY = R.initCode("510008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DESCRIPTION_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_DESCRIPTION_EMPTY = R.initMsg("活动描述不能为空", "SZ0099_MSG_OOD_ACTIVITY_DESCRIPTION_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DESCRIPTION_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_DESCRIPTION_EXTRA_LENGTH = R.initCode("510009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DESCRIPTION_EXTRA_LENGTH");
	public static final String SZ0099_MSG_OOD_ACTIVITY_DESCRIPTION_EXTRA_LENGTH = R.initMsg("活动描述字符数超长", "SZ0099_MSG_OOD_ACTIVITY_DESCRIPTION_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DESCRIPTION_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_BASEINFO_SUCCESS = R.initCode("510010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_BASEINFO_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_BASEINFO_SUCCESS = R.initMsg("更新活动基本信息成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_BASEINFO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_BASEINFO_SUCCESS");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_BUY_NOT_EXIST = R.initCode("510011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACTIVITY_BUY_NOT_EXIST = R.initMsg("您要购买的活动不存在", "SZ0099_MSG_OOD_ACTIVITY_BUY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACTIVITY_BUY_SHELVED_NO = R.initCode("510012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_SHELVED_NO");
	public static final String SZ0099_MSG_OOD_ACTIVITY_BUY_SHELVED_NO = R.initMsg("您要购买的活动已被下架", "SZ0099_MSG_OOD_ACTIVITY_BUY_SHELVED_NO", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_SHELVED_NO");

	public static final String SZ0099_CODE_OOD_ACTIVITY_BUY_HAS_DELTETED = R.initCode("510013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_HAS_DELTETED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_BUY_HAS_DELTETED = R.initMsg("您要购买的活动已被删除", "SZ0099_MSG_OOD_ACTIVITY_BUY_HAS_DELTETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_HAS_DELTETED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_BUY_USER_SELF = R.initCode("510014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_USER_SELF");
	public static final String SZ0099_MSG_OOD_ACTIVITY_BUY_USER_SELF = R.initMsg("您不能购买自己发布的活动", "SZ0099_MSG_OOD_ACTIVITY_BUY_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_BUY_USER_SELF");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_NOT_USER_SELF = R.initCode("510015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NOT_USER_SELF");
	public static final String SZ0099_MSG_OOD_ACTIVITY_NOT_USER_SELF = R.initMsg("您无权修改不是自己的活动", "SZ0099_MSG_OOD_ACTIVITY_NOT_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NOT_USER_SELF");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_UNPUBLISHED_SUCCESS = R.initCode("510016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_UNPUBLISHED_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_UNPUBLISHED_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_UNPUBLISHED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_UNPUBLISHED_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_REFRESH_INVALID = R.initCode("510017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_REFRESH_INVALID");
	public static final String SZ0099_MSG_OOD_ACTIVITY_REFRESH_INVALID = R.initMsg("未超过有效期，不能刷新", "SZ0099_MSG_OOD_ACTIVITY_REFRESH_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_REFRESH_INVALID");

	public static final String SZ0099_CODE_OOD_ACTIVITY_REFRESH_EXTRA = R.initCode("510018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_REFRESH_EXTRA");
	public static final String SZ0099_MSG_OOD_ACTIVITY_REFRESH_EXTRA = R.initMsg("超过365天的活动，不再支持刷新", "SZ0099_MSG_OOD_ACTIVITY_REFRESH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_REFRESH_EXTRA");

	public static final String SZ0099_CODE_OOD_ACTIVITY_REFRESH_SUCCESS = R.initCode("510019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_REFRESH_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_REFRESH_SUCCESS = R.initMsg("刷新成功", "SZ0099_MSG_OOD_ACTIVITY_REFRESH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_REFRESH_SUCCESS");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_PRICEORI_EMPTY = R.initCode("510020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRICEORI_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PRICEORI_EMPTY = R.initMsg("活动原价不能为空", "SZ0099_MSG_OOD_ACTIVITY_PRICEORI_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRICEORI_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PRICECUR_EMPTY = R.initCode("510021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRICECUR_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PRICECUR_EMPTY = R.initMsg("活动现价不能为空", "SZ0099_MSG_OOD_ACTIVITY_PRICECUR_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRICECUR_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_STRATEGY_EMPTY = R.initCode("510022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_STRATEGY_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_STRATEGY_EMPTY = R.initMsg("活动优惠策略不能为空", "SZ0099_MSG_OOD_ACTIVITY_STRATEGY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_STRATEGY_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_GRADE_EMPTY = R.initCode("510023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_GRADE_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_GRADE_EMPTY = R.initMsg("活动等级不能为空", "SZ0099_MSG_OOD_ACTIVITY_GRADE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_GRADE_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_RATES_EMPTY = R.initCode("510024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_RATES_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_RATES_EMPTY = R.initMsg("活动最低优惠折扣不能为空", "SZ0099_MSG_OOD_ACTIVITY_RATES_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_RATES_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_RATES_EXTRA = R.initCode("510025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_RATES_EXTRA");
	public static final String SZ0099_MSG_OOD_ACTIVITY_RATES_EXTRA = R.initMsg("活动最低优惠折扣超出设置范围", "SZ0099_MSG_OOD_ACTIVITY_RATES_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_RATES_EXTRA");

	public static final String SZ0099_CODE_OOD_ACTIVITY_GRADE_MORETHAN_9 = R.initCode("510026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_GRADE_MORETHAN_9");
	public static final String SZ0099_MSG_OOD_ACTIVITY_GRADE_MORETHAN_9 = R.initMsg("活动等级大于9时，请与管理员联系", "SZ0099_MSG_OOD_ACTIVITY_GRADE_MORETHAN_9", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_GRADE_MORETHAN_9");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PULL_METHOD_EMPTY = R.initCode("510027", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_METHOD_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PULL_METHOD_EMPTY = R.initMsg("活动提取方式不能为空", "SZ0099_MSG_OOD_ACTIVITY_PULL_METHOD_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_METHOD_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_LINK_EMPTY = R.initCode("510028", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_LINK_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_LINK_EMPTY = R.initMsg("活动链接不能为空", "SZ0099_MSG_OOD_ACTIVITY_LINK_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_LINK_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_EMPTY = R.initCode("510029", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PULL_CODE_EMPTY = R.initMsg("活动提取密码不能为空", "SZ0099_MSG_OOD_ACTIVITY_PULL_CODE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_USER_NOT_LOGIN = R.initCode("500030", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_OOD_ACTIVITY_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后修改", "SZ0099_MSG_OOD_ACTIVITY_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_TITLE_SUCCESS = R.initCode("510031", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_PRICE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_TITLE_SUCCESS = R.initMsg("更新活动标题成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_PRICE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_PRICE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_DESCRPTION_SUCCESS = R.initCode("510069", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_DESCRPTION_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_DESCRPTION_SUCCESS = R.initMsg("更新活动概要成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_DESCRPTION_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_DESCRPTION_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_LENGTH_LESS_4 = R.initCode("510032", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_LENGTH_LESS_4");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PULL_CODE_LENGTH_LESS_4 = R.initMsg("活动提取密码长度不能小于4位", "SZ0099_MSG_OOD_ACTIVITY_PULL_CODE_LENGTH_LESS_4", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_LENGTH_LESS_4");

	public static final String SZ0099_CODE_OOD_ACTIVITY_LINK_LENGTH_MORE_LONG = R.initCode("510033", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_LINK_LENGTH_MORE_LONG");
	public static final String SZ0099_MSG_OOD_ACTIVITY_LINK_LENGTH_MORE_LONG = R.initMsg("下载链接太长了", "SZ0099_MSG_OOD_ACTIVITY_LINK_LENGTH_MORE_LONG", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_LINK_LENGTH_MORE_LONG");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_LENGTH_TOO_LONG = R.initCode("510034", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_LENGTH_TOO_LONG");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PULL_CODE_LENGTH_TOO_LONG = R.initMsg("活动提取密码长度不能大于10位", "SZ0099_MSG_OOD_ACTIVITY_PULL_CODE_LENGTH_TOO_LONG", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PULL_CODE_LENGTH_TOO_LONG");

	public static final String SZ0099_CODE_OOD_ACTIVITY_EDIT_QUICKLY_SUCCESS = R.initCode("510035", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_EDIT_QUICKLY_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_EDIT_QUICKLY_SUCCESS = R.initMsg("快速编辑保存成功", "SZ0099_MSG_OOD_ACTIVITY_EDIT_QUICKLY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_EDIT_QUICKLY_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_PUBLISH_SUCCESS = R.initCode("510036", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_PUBLISH_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_PUBLISH_SUCCESS = R.initMsg("活动发布成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_PUBLISH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_PUBLISH_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_PUBLISHED = R.initCode("510037", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_PUBLISHED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_HAS_PUBLISHED = R.initMsg("活动已发布", "SZ0099_MSG_OOD_ACTIVITY_MERGE_HAS_PUBLISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_PUBLISHED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_CLOSED = R.initCode("510038", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_CLOSED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_HAS_CLOSED = R.initMsg("活动已关闭，若要开启请联系管理员！", "SZ0099_MSG_OOD_ACTIVITY_MERGE_HAS_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_CLOSED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_CLOSED_SUCCESS = R.initCode("510039", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_CLOSED_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_CLOSED_SUCCESS = R.initMsg("活动关闭成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_CLOSED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_CLOSED_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_NOT_PUBLISH = R.initCode("510040", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NOT_PUBLISH");
	public static final String SZ0099_MSG_OOD_ACTIVITY_NOT_PUBLISH = R.initMsg("活动尚未发布", "SZ0099_MSG_OOD_ACTIVITY_NOT_PUBLISH", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_NOT_PUBLISH");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ACTIVITY_USERID_NULL = R.initCode("510041", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ACTIVITY_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ACTIVITY_USERID_NULL = R.initMsg("活动用户id为空，非法活动，禁止编辑", "SZ0099_MSG_COURSE_PARAGRAGH_ACTIVITY_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ACTIVITY_USERID_NULL");
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL = R.initCode("510042", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_USERID_NULL = R.initMsg("还没登录，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT = R.initCode("510043", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_USERID_CONFLICT = R.initMsg("非本人发布的活动，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_USERID_CONFLICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA = R.initCode("510044", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_TOTAL_EXTRA = R.initMsg("段落总数超限，请减少后再增加", "SZ0099_MSG_COURSE_PARAGRAGH_TOTAL_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST = R.initCode("510045", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_NOT_EXIST = R.initMsg("段落不存在", "SZ0099_MSG_COURSE_PARAGRAGH_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST");

	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS = R.initCode("510046", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_MERGE_SUCCESS = R.initMsg("段落保存成功", "SZ0099_MSG_COURSE_PARAGRAGH_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST = R.initCode("510046", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST = R.initMsg("段落上传数据不存在", "SZ0099_MSG_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS = R.initCode("510047", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_DELETE_SUCCESS = R.initMsg("段落删除成功", "SZ0099_MSG_COURSE_PARAGRAGH_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS = R.initCode("510048", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ADD_SUCCESS = R.initMsg("段落添加成功", "SZ0099_MSG_COURSE_PARAGRAGH_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS = R.initCode("510049", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS = R.initMsg("已全部删除，成功", "SZ0099_MSG_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_SUBTITLE_EXTRA_LENGTH = R.initCode("510050", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_SUBTITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_OOD_ACTIVITY_SUBTITLE_EXTRA_LENGTH = R.initMsg("活动子标题字符数超长", "SZ0099_MSG_OOD_ACTIVITY_SUBTITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_SUBTITLE_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_DELERED_SUCCESS = R.initCode("510058", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_DELERED_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_DELERED_SUCCESS = R.initMsg("活动删除成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_DELERED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_DELERED_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_PRAISE_SUCCESS = R.initCode("510059", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_PRAISE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_PRAISE_SUCCESS = R.initMsg("活动点赞成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_PRAISE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_PRAISE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PRAISE_USER_NOT_LOGIN = R.initCode("510060", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRAISE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PRAISE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后点赞", "SZ0099_MSG_OOD_ACTIVITY_PRAISE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRAISE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PRAISE_EXIST = R.initCode("510061", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRAISE_EXIST");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PRAISE_EXIST = R.initMsg("你已经点过赞了", "SZ0099_MSG_OOD_ACTIVITY_PRAISE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRAISE_EXIST");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PRAISE_USER_SELF_NOALLOW = R.initCode("510062", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRAISE_USER_SELF_NOALLOW");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PRAISE_USER_SELF_NOALLOW = R.initMsg("自己赞自己？还是让别人来点赞吧！", "SZ0099_MSG_OOD_ACTIVITY_PRAISE_USER_SELF_NOALLOW", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PRAISE_USER_SELF_NOALLOW");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_FAVIRATE_SUCCESS = R.initCode("510063", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_FAVIRATE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_FAVIRATE_SUCCESS = R.initMsg("活动收藏成功", "SZ0099_MSG_OOD_ACTIVITY_MERGE_FAVIRATE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_FAVIRATE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_USER_NOT_LOGIN = R.initCode("510064", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_OOD_ACTIVITY_FAVIRATE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后点赞", "SZ0099_MSG_OOD_ACTIVITY_FAVIRATE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_EXIST = R.initCode("510065", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_EXIST");
	public static final String SZ0099_MSG_OOD_ACTIVITY_FAVIRATE_EXIST = R.initMsg("你已经收藏过了", "SZ0099_MSG_OOD_ACTIVITY_FAVIRATE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_EXIST");

	public static final String SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_USER_SELF_NOALLOW = R.initCode("510066", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_USER_SELF_NOALLOW");
	public static final String SZ0099_MSG_OOD_ACTIVITY_FAVIRATE_USER_SELF_NOALLOW = R.initMsg("自己的也收藏？让别人收藏吧！", "SZ0099_MSG_OOD_ACTIVITY_FAVIRATE_USER_SELF_NOALLOW", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_FAVIRATE_USER_SELF_NOALLOW");

	public static final String SZ0099_CODE_OOD_ACTIVITY_CATEGORY_EMPTY = R.initCode("510067", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_CATEGORY_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_CATEGORY_EMPTY = R.initMsg("活动还没选择分类", "SZ0099_MSG_OOD_ACTIVITY_CATEGORY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_CATEGORY_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PUBLISHED_NO_COVER = R.initCode("510068", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PUBLISHED_NO_COVER");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PUBLISHED_NO_COVER = R.initMsg("没有上传封面图", "SZ0099_MSG_OOD_ACTIVITY_PUBLISHED_NO_COVER", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PUBLISHED_NO_COVER");

	public static final String SZ0099_CODE_OOD_ACTIVITY_ORGANIZE_EMPTY = R.initCode("510069", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORGANIZE_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_ORGANIZE_EMPTY = R.initMsg("活动组织形式尚未选择", "SZ0099_MSG_OOD_ACTIVITY_ORGANIZE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_ORGANIZE_EMPTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_SAVE_SUCCESS = R.initCode("510070", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_SAVE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_SAVE_SUCCESS = R.initMsg("模板设置成功", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_SAVE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_SAVE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_MAXNUM_EXTRA = R.initCode("510071", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_MAXNUM_EXTRA");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_MAXNUM_EXTRA = R.initMsg("模板数已超限", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_MAXNUM_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_MAXNUM_EXTRA");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_LOAD_SUCCESS = R.initCode("510072", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_LOAD_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_LOAD_SUCCESS = R.initMsg("模板载入成功", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_LOAD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_LOAD_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_ID_EMPLTY = R.initCode("510073", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_ID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_ID_EMPLTY = R.initMsg("模板ID为空", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_ID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_ID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_ID_NOT_EXIST = R.initCode("510074", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_ID_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_ID_NOT_EXIST = R.initMsg("模板ID不存在", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_ID_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_ID_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_NOTA = R.initCode("510075", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_NOTA");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_NOTA = R.initMsg("要载入的不是模板，请检查设置", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_NOTA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_NOTA");

	public static final String SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_NOT_COMMON = R.initCode("510076", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_NOT_COMMON");
	public static final String SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_NOT_COMMON = R.initMsg("要载入的模板属于私有，无权载入", "SZ0099_MSG_OOD_ACTIVITY_TEMPLATE_NOT_COMMON", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_TEMPLATE_NOT_COMMON");

	public static final String SZ0099_CODE_OOD_ACTIVITY_DIFFICULTY_INVALID = R.initCode("510077", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DIFFICULTY_INVALID");
	public static final String SZ0099_MSG_OOD_ACTIVITY_DIFFICULTY_INVALID = R.initMsg("难度系数须在0-99之间", "SZ0099_MSG_OOD_ACTIVITY_DIFFICULTY_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_DIFFICULTY_INVALID");

	
	
	
	public static final String SZ0099_CODE_OOD_ACTIVITYID_EMPTY = R.initCode("511005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITYID_EMPTY");
	public static final String SZ0099_MSG_OOD_ACTIVITYID_EMPTY = R.initMsg("添加标签时，活动ID不能为空", "SZ0099_MSG_OOD_ACTIVITYID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITYID_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_DELETE_ARTICLEID_EMPTY = R.initCode("511009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_DELETE_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_DELETE_ARTICLEID_EMPTY = R.initMsg("删除标签时，活动ID不能为空", "SZ0099_MSG_COURSE_DELETE_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_DELETE_ARTICLEID_EMPTY");

	
	
	
	//------------------------------
	

	
	
	
	public static final String SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_SUCCESS = R.initCode("512100", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_EMPLTY = R.initCode("512106", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_EMPLTY = R.initMsg("用户id为空，请登录再试", "SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_EMPLTY = R.initCode("512101", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_EMPLTY = R.initMsg("此操作id不能为空", "SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY = R.initCode("512102", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY = R.initMsg("查无此实体", "SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_INVALID = R.initCode("512103", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_INVALID");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_INVALID = R.initMsg("非法操作用户", "SZ0099_MSG_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PARAGRAGH_PHOTO_USERID_INVALID");

	
	public static final String SZ0099_CODE_OOD_ACTIVITY_PHOTO_MAINID_EMPLTY = R.initCode("512104", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PHOTO_MAINID_EMPLTY");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PHOTO_MAINID_EMPLTY = R.initMsg("所绑定的活动ID为空", "SZ0099_MSG_OOD_ACTIVITY_PHOTO_MAINID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PHOTO_MAINID_EMPLTY");

	public static final String SZ0099_CODE_OOD_ACTIVITY_PHOTO_MAINNUM_EXTRA = R.initCode("512105", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PHOTO_MAINNUM_EXTRA");
	public static final String SZ0099_MSG_OOD_ACTIVITY_PHOTO_MAINNUM_EXTRA = R.initMsg("图片数量超限", "SZ0099_MSG_OOD_ACTIVITY_PHOTO_MAINNUM_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_PHOTO_MAINNUM_EXTRA");

	public static final String SZ0099_CODE_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_MERGE_SUCESS = R.initCode("512107", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_MERGE_SUCESS");
	public static final String SZ0099_MSG_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_MERGE_SUCESS = R.initMsg("模板设置成功", "SZ0099_MSG_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_MERGE_SUCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_MERGE_SUCESS");
	
	public static final String SZ0099_CODE_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_CANCEL_SUCESS = R.initCode("512108", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_CANCEL_SUCESS");
	public static final String SZ0099_MSG_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_CANCEL_SUCESS = R.initMsg("模板取消成功", "SZ0099_MSG_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_CANCEL_SUCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_PARAGRAGH_PHOTO_TEMPLATE_CANCEL_SUCESS");
	
	public static final String SZ0099_CODE_OOD_ACTIVITY_USER_NOT_SELF = R.initCode("512109", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_USER_NOT_SELF");
	public static final String SZ0099_MSG_OOD_ACTIVITY_USER_NOT_SELF = R.initMsg("允许编辑自己发布的活动！", "SZ0099_MSG_OOD_ACTIVITY_USER_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_USER_NOT_SELF");

	
	
	
	
	//------------------
	
	public static final String SZ0099_CODE_COURSE_PERSONAL_ACTIVITY_EXTRA = R.initCode("530003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ACTIVITY_EXTRA");
	public static final String SZ0099_MSG_COURSE_PERSONAL_ACTIVITY_EXTRA = R.initMsg("活动数已经满了", "SZ0099_MSG_COURSE_PERSONAL_ACTIVITY_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ACTIVITY_EXTRA");

	public static final String SZ0099_CODE_COURSE_PERSONAL_ACTIVITY_NOT_EXIST = R.initCode("530004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ACTIVITY_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PERSONAL_ACTIVITY_NOT_EXIST = R.initMsg("您要查询的活动不存在", "SZ0099_MSG_COURSE_PERSONAL_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_ACTIVITY_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_ACTIVITY_USERID_NULL = R.initCode("530005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_ACTIVITY_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_PERSONAL_ACTIVITY_USERID_NULL = R.initMsg("用户id为空，非法活动，禁止修炼", "SZ0099_MSG_COURSE_PARAGRAGH_PERSONAL_ACTIVITY_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_ACTIVITY_USERID_NULL");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ACTIVITY_USERID_CONFLICT = R.initCode("530006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ACTIVITY_USERID_CONFLICT");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ACTIVITY_USERID_CONFLICT = R.initMsg("非本人活动，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_ACTIVITY_USERID_CONFLICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ACTIVITY_USERID_CONFLICT");

	public static final String SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_DELERED = R.initCode("530007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_DELERED");
	public static final String SZ0099_MSG_OOD_ACTIVITY_MERGE_HAS_DELERED = R.initMsg("活动已被删除！", "SZ0099_MSG_OOD_ACTIVITY_MERGE_HAS_DELERED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_MERGE_HAS_DELERED");

	public static final String SZ0099_CODE_OOD_ACTIVITY_RESET_ORDER_SUCCESS = R.initCode("530008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_RESET_ORDER_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACTIVITY_RESET_ORDER_SUCCESS = R.initMsg("活动序号已重排！", "SZ0099_MSG_OOD_ACTIVITY_RESET_ORDER_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACTIVITY_RESET_ORDER_SUCCESS");


	public static final String SZ0099_CODE_COURSE_TAG_ARTICLEID_EMPTY = R.initCode("531005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_ARTICLEID_EMPTY = R.initMsg("添加标签时，活动ID不能为空", "SZ0099_MSG_COURSE_TAG_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ARTICLEID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_DELETE_ARTICLEID_EMPTY = R.initCode("531009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_ARTICLEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_DELETE_ARTICLEID_EMPTY = R.initMsg("删除标签时，活动ID不能为空", "SZ0099_MSG_COURSE_TAG_DELETE_ARTICLEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_ARTICLEID_EMPTY");

	
	public static final String SZ0099_CODE_OOD_ACT_TIME_ACTIVITYID_EMPTY = R.initCode("531100", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ACTIVITYID_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_TIME_ACTIVITYID_EMPTY = R.initMsg("活动ID不能为空", "SZ0099_MSG_OOD_ACT_TIME_ACTIVITYID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ACTIVITYID_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_TIME_SAVED_SUCCESS = R.initCode("531101", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_SAVED_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_TIME_SAVED_SUCCESS = R.initMsg("时间保存成功", "SZ0099_MSG_OOD_ACT_TIME_SAVED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_SAVED_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_TIME_DELETE_SUCCESS = R.initCode("531102", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_DELETE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_TIME_DELETE_SUCCESS = R.initMsg("时间删除成功", "SZ0099_MSG_OOD_ACT_TIME_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_DELETE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_TIME_ACTIVITY_NOT_EXIST = R.initCode("531104", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ACTIVITY_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACT_TIME_ACTIVITY_NOT_EXIST = R.initMsg("活动不存在", "SZ0099_MSG_OOD_ACT_TIME_ACTIVITY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ACTIVITY_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACT_TIME_ID_EMPTY = R.initCode("531105", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ID_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_TIME_ID_EMPTY = R.initMsg("时间ID为空", "SZ0099_MSG_OOD_ACT_TIME_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ID_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_TIME_BEGINTIME_EMPTY = R.initCode("531106", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_BEGINTIME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_TIME_BEGINTIME_EMPTY = R.initMsg("活动开始时间不能为空", "SZ0099_MSG_OOD_ACT_TIME_BEGINTIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_BEGINTIME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_TIME_ID_NOT_EXIST = R.initCode("531107", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ID_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACT_TIME_ID_NOT_EXIST = R.initMsg("活动时间不存在", "SZ0099_MSG_OOD_ACT_TIME_ID_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ID_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACT_TIME_ENDTIME_EMPTY = R.initCode("531108", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ENDTIME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_TIME_ENDTIME_EMPTY = R.initMsg("活动结束时间不能为空", "SZ0099_MSG_OOD_ACT_TIME_ENDTIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ENDTIME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_TIME_OFFTIME_EMPTY = R.initCode("531109", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_OFFTIME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_TIME_OFFTIME_EMPTY = R.initMsg("活动报名截止时间不能为空", "SZ0099_MSG_OOD_ACT_TIME_OFFTIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_OFFTIME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_TIME_BEGINTIME_MERGE_SUCCESS = R.initCode("531110", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_BEGINTIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_TIME_BEGINTIME_MERGE_SUCCESS = R.initMsg("活动开始时间设置成功", "SZ0099_MSG_OOD_ACT_TIME_BEGINTIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_BEGINTIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_TIME_ENDTIME_MERGE_SUCCESS = R.initCode("531111", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ENDTIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_TIME_ENDTIME_MERGE_SUCCESS = R.initMsg("活动结束时间设置成功",  "SZ0099_MSG_OOD_ACT_TIME_ENDTIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_ENDTIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_TIME_OFFTIME_MERGE_SUCCESS = R.initCode("531112", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_OFFTIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_TIME_OFFTIME_MERGE_SUCCESS = R.initMsg("活动报名截止时间设置成功",  "SZ0099_MSG_OOD_ACT_TIME_OFFTIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_OFFTIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_TIME_BENGINTIME_GT_ENDTIME = R.initCode("531113", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_BENGINTIME_GT_ENDTIME");
	public static final String SZ0099_MSG_OOD_ACT_TIME_BENGINTIME_GT_ENDTIME = R.initMsg("活动开始时间不能大于结束时间",  "SZ0099_MSG_OOD_ACT_TIME_BENGINTIME_GT_ENDTIME", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_BENGINTIME_GT_ENDTIME");

	public static final String SZ0099_CODE_OOD_ACT_TIME_OFFTIME_GT_ENDTIME = R.initCode("531114", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_OFFTIME_GT_ENDTIME");
	public static final String SZ0099_MSG_OOD_ACT_TIME_OFFTIME_GT_ENDTIME = R.initMsg("活动报名截止时间不能大于结束时间",  "SZ0099_MSG_OOD_ACT_TIME_OFFTIME_GT_ENDTIME", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_TIME_OFFTIME_GT_ENDTIME");

	
	
	
	public static final String SZ0099_CODE_OOD_JOINITEM_JOINTIME_EMPTY = R.initCode("531200", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_JOINTIME_EMPTY");
	public static final String SZ0099_MSG_OOD_JOINITEM_JOINTIME_EMPTY = R.initMsg("集合时间不能为空", "SZ0099_MSG_OOD_JOINITEM_JOINTIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_JOINTIME_EMPTY");

	public static final String SZ0099_CODE_OOD_JOINITEM_JOINTIME_MERGE_SUCCESS = R.initCode("531201", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_JOINTIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_JOINITEM_JOINTIME_MERGE_SUCCESS = R.initMsg("集合时间设置成功",  "SZ0099_MSG_OOD_JOINITEM_JOINTIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_JOINTIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_JOINITEM_ID_NOT_EXIST = R.initCode("531202", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_ID_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_JOINITEM_ID_NOT_EXIST = R.initMsg("集合ID不存在", "SZ0099_MSG_OOD_JOINITEM_ID_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_ID_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_JOINITEM_PLACE_MERGE_SUCCESS = R.initCode("531203", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_JOINITEM_PLACE_MERGE_SUCCESS = R.initMsg("集合地点更新成功",  "SZ0099_MSG_OOD_JOINITEM_PLACE_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_JOINITEM_DESCRIPTION_MERGE_SUCCESS = R.initCode("531204", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_DESCRIPTION_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_JOINITEM_DESCRIPTION_MERGE_SUCCESS = R.initMsg("集合补充说明已保存",  "SZ0099_MSG_OOD_JOINITEM_DESCRIPTION_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_DESCRIPTION_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_JOINITEM_PLACE_EMPTY = R.initCode("531205", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_EMPTY");
	public static final String SZ0099_MSG_OOD_JOINITEM_PLACE_EMPTY = R.initMsg("集合地点不能为空", "SZ0099_MSG_OOD_JOINITEM_PLACE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_EMPTY");

	public static final String SZ0099_CODE_OOD_JOINITEM_PLACE_LENGTH_EXTRA = R.initCode("531206", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_LENGTH_EXTRA");
	public static final String SZ0099_MSG_OOD_JOINITEM_PLACE_LENGTH_EXTRA  = R.initMsg("集合地点超长，如有多余信息在补充说明书写", "SZ0099_MSG_OOD_JOINITEM_PLACE_LENGTH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_LENGTH_EXTRA");

	public static final String SZ0099_CODE_OOD_JOINITEM_DESCRIPTION_LENGTH_EXTRA = R.initCode("531207", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_DESCRIPTION_LENGTH_EXTRA");
	public static final String SZ0099_MSG_OOD_JOINITEM_DESCRIPTION_LENGTH_EXTRA = R.initMsg("集合补充说明超长",  "SZ0099_MSG_OOD_JOINITEM_DESCRIPTION_LENGTH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_DESCRIPTION_LENGTH_EXTRA");

	
	public static final String SZ0099_CODE_OOD_JOINITEM_DELETE_SUCCESS = R.initCode("531208", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_DELETE_SUCCESS");
	public static final String SZ0099_MSG_OOD_JOINITEM_DELETE_SUCCESS = R.initMsg("集合信息删除成功",  "SZ0099_MSG_OOD_JOINITEM_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_DELETE_SUCCESS");

	public static final String SZ0099_CODE_OOD_JOINITEM_ADD_SUCCESS = R.initCode("531209", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_ADD_SUCCESS");
	public static final String SZ0099_MSG_OOD_JOINITEM_ADD_SUCCESS = R.initMsg("集合信息添加成功",  "SZ0099_MSG_OOD_JOINITEM_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_ADD_SUCCESS");

	public static final String SZ0099_CODE_OOD_JOINITEM_EMPTY = R.initCode("531210", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_EMPTY");
	public static final String SZ0099_MSG_OOD_JOINITEM_EMPTY = R.initMsg("集合信息尚未设置",  "SZ0099_MSG_OOD_JOINITEM_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_EMPTY");


	
	
	public static final String SZ0099_CODE_OOD_ACT_FEE_CURRENCY_EMPTY = R.initCode("531300", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_CURRENCY_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_FEE_CURRENCY_EMPTY = R.initMsg("货币类型不能为空", "SZ0099_MSG_OOD_ACT_FEE_CURRENCY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_CURRENCY_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_FEE_FEETYPE_EMPTY = R.initCode("531301", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_FEE_FEETYPE_EMPTY = R.initMsg("分摊类型不能为空", "SZ0099_MSG_OOD_ACT_FEE_FEETYPE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_FEE_CURRENCY_NOT_RMB = R.initCode("531302", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_CURRENCY_NOT_RMB");
	public static final String SZ0099_MSG_OOD_ACT_FEE_CURRENCY_NOT_RMB = R.initMsg("货币类型目前仅支持RMB", "SZ0099_MSG_OOD_ACT_FEE_CURRENCY_NOT_RMB", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_CURRENCY_NOT_RMB");

	public static final String SZ0099_CODE_OOD_ACT_FEE_ID_EMPTY = R.initCode("531303", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_ID_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_FEE_ID_EMPTY = R.initMsg("费用ID为空", "SZ0099_MSG_OOD_ACT_FEE_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_ID_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_FEE_DESCRIPTION_LENGTH_EXTRA = R.initCode("531304", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_DESCRIPTION_LENGTH_EXTRA");
	public static final String SZ0099_MSG_OOD_ACT_FEE_DESCRIPTION_LENGTH_EXTRA = R.initMsg("费用说明长度超限", "SZ0099_MSG_OOD_ACT_FEE_DESCRIPTION_LENGTH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_DESCRIPTION_LENGTH_EXTRA");

	public static final String SZ0099_CODE_OOD_ACT_FEE_DESCRIPTION_MERGE_SUCCESS = R.initCode("531305", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_DESCRIPTION_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_FEE_DESCRIPTION_MERGE_SUCCESS = R.initMsg("费用说明保存成功", "SZ0099_MSG_OOD_ACT_FEE_DESCRIPTION_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_DESCRIPTION_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_FEE_MERGE_SUCCESS = R.initCode("531306", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_FEE_MERGE_SUCCESS = R.initMsg("费用信息保存成功", "SZ0099_MSG_OOD_ACT_FEE_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_FEE_EMPTY = R.initCode("531307", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_FEE_EMPTY = R.initMsg("费用信息尚未设置",  "SZ0099_MSG_OOD_ACT_FEE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_FEE_CURRENCY_RMB_ONLY = R.initCode("531308", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_CURRENCY_RMB_ONLY");
	public static final String SZ0099_MSG_OOD_ACT_FEE_CURRENCY_RMB_ONLY = R.initMsg("当前只支持RMB人民币！",  "SZ0099_MSG_OOD_ACT_FEE_CURRENCY_RMB_ONLY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_CURRENCY_RMB_ONLY");

	public static final String SZ0099_CODE_OOD_ACT_FEE_RMBAMOUNT_GTE_0 = R.initCode("531309", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_RMBAMOUNT_GT_0");
	public static final String SZ0099_MSG_OOD_ACT_FEE_RMBAMOUNT_GTE_0 = R.initMsg("报名费金额不能小于0！",  "SZ0099_MSG_OOD_ACT_FEE_RMBAMOUNT_GT_0", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_RMBAMOUNT_GT_0");

	public static final String SZ0099_CODE_OOD_ACT_FEE_RMBAMOUNTORI_GTE_0 = R.initCode("531310", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_RMBAMOUNTORI_GTE_0");
	public static final String SZ0099_MSG_OOD_ACT_FEE_RMBAMOUNTORI_GTE_0 = R.initMsg("原价不能小于0！",  "SZ0099_MSG_OOD_ACT_FEE_RMBAMOUNTORI_GTE_0", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_RMBAMOUNTORI_GTE_0");

	public static final String SZ0099_CODE_OOD_ACT_FEE_FEETYPE_AA_LTE_100 = R.initCode("531311", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_AA_LTE_100");
	public static final String SZ0099_MSG_OOD_ACT_FEE_FEETYPE_AA_LTE_100 = R.initMsg("AA制活动，费用不能少于100分（1元）", "SZ0099_MSG_OOD_ACT_FEE_FEETYPE_AA_LTE_100", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_AA_LTE_100");

	public static final String SZ0099_CODE_OOD_ACT_FEE_FEETYPE_FREE_MUST_0 = R.initCode("531312", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_FREE_MUST_0");
	public static final String SZ0099_MSG_OOD_ACT_FEE_FEETYPE_FREE_MUST_0 = R.initMsg("免费活动，费用必须为0分", "SZ0099_MSG_OOD_ACT_FEE_FEETYPE_FREE_MUST_0", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_FREE_MUST_0");

	public static final String SZ0099_CODE_OOD_ACT_FEE_FEETYPE_SELF_LTE_1000 = R.initCode("531313", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_SELF_LTE_1000");
	public static final String SZ0099_MSG_OOD_ACT_FEE_FEETYPE_SELF_LTE_1000 = R.initMsg("自助活动，费用不能少于1000分（10元）", "SZ0099_MSG_OOD_ACT_FEE_FEETYPE_SELF_LTE_1000", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_FEE_FEETYPE_SELF_LTE_1000");

	
	
	public static final String SZ0099_CODE_OOD_ACT_ORDER_PAYTIME_EMPTY = R.initCode("531400", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_PAYTIME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_PAYTIME_EMPTY = R.initMsg("活动订单支付时间不能为空", "SZ0099_MSG_OOD_ACT_ORDER_PAYTIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_PAYTIME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_ID_NOT_EXIST = R.initCode("531401", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_ID_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_ID_NOT_EXIST = R.initMsg("活动订单不存在", "SZ0099_MSG_OOD_ACT_ORDER_ID_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_ID_NOT_EXIST");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_ID_EMPTY = R.initCode("531404", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_ID_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_ID_EMPTY = R.initMsg("活动订单ID不能为空", "SZ0099_MSG_OOD_ACT_ORDER_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_ID_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_EXETIME_EMPTY = R.initCode("531402", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_EXETIME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_EXETIME_EMPTY = R.initMsg("活动订单出行时间不能为空", "SZ0099_MSG_OOD_ACT_ORDER_EXETIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_EXETIME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_FINISHTIME_EMPTY = R.initCode("531403", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_FINISHTIME_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_FINISHTIME_EMPTY = R.initMsg("活动订单完成时间不能为空", "SZ0099_MSG_OOD_ACT_ORDER_FINISHTIME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_FINISHTIME_EMPTY");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_MAINID_EMPTY = R.initCode("531405", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_MAINID_EMPTY");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_MAINID_EMPTY = R.initMsg("活动ID不能为空", "SZ0099_MSG_OOD_ACT_ORDER_MAINID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_MAINID_EMPTY");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_PAYTIME_MERGE_SUCCESS = R.initCode("531406", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_PAYTIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_PAYTIME_MERGE_SUCCESS = R.initMsg("活动订单支付时间设置成功",  "SZ0099_MSG_OOD_ORDER_ACT_PAYTIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_PAYTIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_EXETIME_MERGE_SUCCESS = R.initCode("531407", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_EXETIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_EXETIME_MERGE_SUCCESS = R.initMsg("活动订单出行时间设置成功",  "SZ0099_MSG_OOD_ORDER_ACT_EXETIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_EXETIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_FINISHTIME_MERGE_SUCCESS = R.initCode("531408", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_FINISHTIME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_FINISHTIME_MERGE_SUCCESS = R.initMsg("活动订单完成时间设置成功",  "SZ0099_MSG_OOD_ORDER_ACT_FINISHTIME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_FINISHTIME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_SAVED_SUCCESS = R.initCode("531409", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_SAVED_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_SAVED_SUCCESS = R.initMsg("活动订单初始化成功", "SZ0099_MSG_OOD_ACT_ORDER_SAVED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_SAVED_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_DELETE_SUCCESS = R.initCode("531410", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_DELETE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_DELETE_SUCCESS = R.initMsg("活动订单删除成功", "SZ0099_MSG_OOD_ACT_ORDER_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_DELETE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_CONFIRM_SUCCESS = R.initCode("531411", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_CONFIRM_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_CONFIRM_SUCCESS = R.initMsg("活动订单确认成功", "SZ0099_MSG_OOD_ACT_ORDER_CONFIRM_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_CONFIRM_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_STATUS_INVALID = R.initCode("531412", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_STATUS_INVALID");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_STATUS_INVALID = R.initMsg("活动订单状态已确认过，无需重复确认", "SZ0099_MSG_OOD_ACT_ORDER_STATUS_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_STATUS_INVALID");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_TIMEOUT_EXTRA = R.initCode("531413", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_TIMEOUT_EXTRA");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_TIMEOUT_EXTRA = R.initMsg("订单支付已超时，请重新下单", "SZ0099_MSG_OOD_ACT_ORDER_TIMEOUT_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_TIMEOUT_EXTRA");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_STATUS_CHANGED = R.initCode("531414", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_STATUS_CHANGED");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_STATUS_CHANGED = R.initMsg("活动订单状态已变化，请重新下单", "SZ0099_MSG_OOD_ACT_ORDER_STATUS_CHANGED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_STATUS_CHANGED");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_STATUS_CANNOT_CANCEL = R.initCode("531415", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_STATUS_CANNOT_CANCEL");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_STATUS_CANNOT_CANCEL = R.initMsg("该订单状态下不能取消", "SZ0099_MSG_OOD_ACT_ORDER_STATUS_CANNOT_CANCEL", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_STATUS_CANNOT_CANCEL");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_CANCEL_SUCCESS = R.initCode("531416", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_CANCEL_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_CANCEL_SUCCESS = R.initMsg("活动订单取消成功", "SZ0099_MSG_OOD_ACT_ORDER_CANCEL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_CANCEL_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_USER_UPTO_MAXNUM = R.initCode("531417", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_USER_UPTO_MAXNUM");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_USER_UPTO_MAXNUM = R.initMsg("活动报名人数已达上限", "SZ0099_MSG_OOD_ACT_ORDER_USER_UPTO_MAXNUM", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_USER_UPTO_MAXNUM");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_OFFTIME_END = R.initCode("531418", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_OFFTIME_END");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_OFFTIME_END = R.initMsg("活动报名已截止", "SZ0099_MSG_OOD_ACT_ORDER_OFFTIME_END", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_OFFTIME_END");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_WHENPAY_STATUS_INVALID = R.initCode("531419", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_WHENPAY_STATUS_INVALID");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_WHENPAY_STATUS_INVALID = R.initMsg("订单状态不正确", "SZ0099_MSG_OOD_ACT_ORDER_WHENPAY_STATUS_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_WHENPAY_STATUS_INVALID");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_WAIT_RUN_DIRECTORY = R.initCode("531420", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_WAIT_RUN_DIRECTORY");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_WAIT_RUN_DIRECTORY = R.initMsg("订单状态：等待出行", "SZ0099_MSG_OOD_ACT_ORDER_WAIT_RUN_DIRECTORY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_WAIT_RUN_DIRECTORY");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_HAS_CANCELED = R.initCode("531421", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_CANCELED");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_HAS_CANCELED = R.initMsg("订单已取消", "SZ0099_MSG_OOD_ACT_ORDER_HAS_CANCELED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_CANCELED");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_HAS_PAY_SUCCESS = R.initCode("531422", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_PAY_SUCCESS");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_HAS_PAY_SUCCESS = R.initMsg("订单已支付成功", "SZ0099_MSG_OOD_ACT_ORDER_HAS_PAY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_PAY_SUCCESS");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_HAS_CLOSED = R.initCode("531423", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_CLOSED");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_HAS_CLOSED = R.initMsg("订单已关闭", "SZ0099_MSG_OOD_ACT_ORDER_HAS_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_CLOSED");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_HAS_SENT = R.initCode("531424", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_SENT");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_HAS_SENT = R.initMsg("订单已发送", "SZ0099_MSG_OOD_ACT_ORDER_HAS_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_HAS_SENT");

	public static final String SZ0099_CODE_OOD_ACT_ORDER_PAYING = R.initCode("531425", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_PAYING");
	public static final String SZ0099_MSG_OOD_ACT_ORDER_PAYING = R.initMsg("订单支付中", "SZ0099_MSG_OOD_ACT_ORDER_PAYING", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ACT_ORDER_PAYING");

	
	
	
	
	
	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_EMPTY = R.initCode("531450", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_EMPTY");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_EMPTY = R.initMsg("活动用户不能为空", "SZ0099_MSG_OOD_ORDER_ACT_USER_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_EMPTY");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_EMPTY = R.initCode("531451", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_EMPTY");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_MOBILE_EMPTY = R.initMsg("手机号不能为空", "SZ0099_MSG_OOD_ORDER_ACT_USER_MOBILE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_EMPTY");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_ID_EMPTY = R.initCode("531452", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_ID_EMPTY");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_ID_EMPTY = R.initMsg("活动用户ID不能为空", "SZ0099_MSG_OOD_ORDER_ACT_USER_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_ID_EMPTY");

	
	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_EMPTY = R.initCode("531453", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_EMPTY");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_REALNAME_EMPTY = R.initMsg("真实姓名不能为空", "SZ0099_MSG_OOD_ORDER_ACT_USER_REALNAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_EMPTY");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_LENGTH_EXTRA = R.initCode("531454", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_LENGTH_EXTRA");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_REALNAME_LENGTH_EXTRA  = R.initMsg("真实姓名超长", "SZ0099_MSG_OOD_JOINITEM_PLACE_LENGTH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_JOINITEM_PLACE_LENGTH_EXTRA");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_INVALID = R.initCode("531455", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_INVALID");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_MOBILE_INVALID = R.initMsg("手机号格式不正确", "SZ0099_MSG_OOD_ORDER_ACT_USER_MOBILE_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_INVALID");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_NOT_EXIST = R.initCode("531456", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_NOT_EXIST = R.initMsg("活动用户不存在", "SZ0099_MSG_OOD_ORDER_ACT_USER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_NOT_EXIST");

	
	
	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_EMPTY = R.initCode("531457", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_EMPTY");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_EMPTY = R.initMsg("身份证号不能为空", "SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_EMPTY");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_INVALID = R.initCode("531458", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_INVALID");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_INVALID = R.initMsg("身份证号格式不正确", "SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_INVALID");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_BASEID_EMPTY = R.initCode("531459", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_BASEID_EMPTY");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_BASEID_EMPTY = R.initMsg("活动用户所属订单ID不能为空", "SZ0099_MSG_OOD_ORDER_ACT_USER_BASEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_BASEID_EMPTY");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_MERGE_SUCCESS = R.initCode("531460", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_MERGE_SUCCESS = R.initMsg("身份证号保存成功", "SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_MERGE_SUCCESS = R.initCode("531461", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_REALNAME_MERGE_SUCCESS = R.initMsg("真实姓名保存成功", "SZ0099_MSG_OOD_ORDER_ACT_USER_REALNAME_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_REALNAME_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_MERGE_SUCCESS = R.initCode("531462", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_MERGE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_MOBILE_MERGE_SUCCESS = R.initMsg("手机号保存成功", "SZ0099_MSG_OOD_ORDER_ACT_USER_MOBILE_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_MOBILE_MERGE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_ADD_SUCCESS = R.initCode("531463", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_ADD_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_ADD_SUCCESS = R.initMsg("用户添加成功", "SZ0099_MSG_OOD_ORDER_ACT_USER_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_ADD_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_DELETE_SUCCESS = R.initCode("531464", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_DELETE_SUCCESS");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_DELETE_SUCCESS = R.initMsg("用户删除成功", "SZ0099_MSG_OOD_ORDER_ACT_USER_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_DELETE_SUCCESS");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_HAS_CONFIRMED = R.initCode("531465", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_HAS_CONFIRMED");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_HAS_CONFIRMED = R.initMsg("该用户已经确认过报名了", "SZ0099_MSG_OOD_ORDER_ACT_USER_HAS_CONFIRMED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_HAS_CONFIRMED");

	
	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_EXIST = R.initCode("531466", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_EXIST");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_EXIST = R.initMsg("身份证号已存在", "SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_EXIST");
	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_REPEATED = R.initCode("531467", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_REPEATED");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_REPEATED = R.initMsg("身份证号有重复", "SZ0099_MSG_OOD_ORDER_ACT_USER_IDENTITY_REPEATED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_IDENTITY_REPEATED");

	public static final String SZ0099_CODE_OOD_ORDER_ACT_USER_REPEATED_CONFIRMED = R.initCode("531468", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_REPEATED_CONFIRMED");
	public static final String SZ0099_MSG_OOD_ORDER_ACT_USER_REPEATED_CONFIRMED = R.initMsg("该用户已经报过名了，请详查后确认是否重复报名！", "SZ0099_MSG_OOD_ORDER_ACT_USER_REPEATED_CONFIRMED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_ORDER_ACT_USER_REPEATED_CONFIRMED");

	
}
