/**
 * Jit8j framework support by bruce yang 
 * contact email: 275060435@qq.com
 */
package dml.sz0099.course.app.module.define;

import org.jit4j.app.module.define.R;

/**
 * <pre>
 * @formatter:off
 *
 * 课程产品模块响应码
 * @author bruce yang at 2018-09-04 09:01:29
 * 
 * ----------------------------------------------------------------------------------------
 * Requirement		Author		Date		Function
 * init				bruceyang	2018-09-04	basic init
 * 
 * @formatter:on
 * </pre>
 */

public class CourseProductRespCode extends CourseRespCode {


	// 定义模块名, 课程产品模块

	public static final String SZ0099_CODE_COURSE_PRODUCT_SUCCESS = R.initCode("200001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_SUCCESS = R.initMsg("产品操作成功", "SZ0099_MSG_COURSE_PRODUCT_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_SUCCESS = R.initCode("200002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_SUCCESS = R.initMsg("您的订单已生成，请等待客服验证确认后发货", "SZ0099_MSG_COURSE_PRODUCT_ORDER_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_SUCCESS");


	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_NOT_EXIST = R.initCode("200003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_NOT_EXIST = R.initMsg("该订单不存在，参数错误", "SZ0099_MSG_COURSE_PRODUCT_ORDER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_NOT_LOGIN = R.initCode("200004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后下单", "SZ0099_MSG_COURSE_PRODUCT_ORDER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_USERID_CONFICT = R.initCode("200005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_USERID_CONFICT");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_USERID_CONFICT = R.initMsg("您预下单的身份与确认订单的身份不符，请使用相同帐号下单", "SZ0099_MSG_COURSE_PRODUCT_ORDER_USERID_CONFICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_USERID_CONFICT");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_PAYED = R.initCode("200006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_PAYED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_PAYED = R.initMsg("您的订单已经执行过支付操作了，请确认微信钱包或支付宝交易流水是否已打款", "SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_PAYED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_PAYED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_SENT = R.initCode("200007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_SENT");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_SENT = R.initMsg("您的订单已发货，请注意查收", "SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_SENT");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_RECIEVED = R.initCode("200008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_RECIEVED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_RECIEVED = R.initMsg("您的订单已签收", "SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_RECIEVED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_RECIEVED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_TM_RECIEVED = R.initCode("200009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_TM_RECIEVED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_TM_RECIEVED = R.initMsg("您的订单已超时签收", "SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_TM_RECIEVED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_TM_RECIEVED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_INPROCESS = R.initCode("200010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_INPROCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_INPROCESS = R.initMsg("您的订单已被客服处理中，敬请等待一下", "SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_INPROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_INPROCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_BUY_INSTRUCTION_SUCCESS = R.initCode("200011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_INSTRUCTION_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_BUY_INSTRUCTION_SUCCESS = R.initMsg("购买说明查看成功", "SZ0099_MSG_COURSE_PRODUCT_BUY_INSTRUCTION_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_INSTRUCTION_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_FLOWERID_SUCCESS = R.initCode("200012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_FLOWERID_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_FLOWERID_SUCCESS = R.initMsg("订单流水号生成成功", "SZ0099_MSG_COURSE_PRODUCT_ORDER_FLOWERID_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_FLOWERID_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_INVALID_USERID = R.initCode("200013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_INVALID_USERID");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_INVALID_USERID = R.initMsg("订单身份不合法", "SZ0099_MSG_COURSE_PRODUCT_ORDER_INVALID_USERID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_INVALID_USERID");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_NO_SENT = R.initCode("200014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NO_SENT");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_NO_SENT = R.initMsg("该订单尚未被客服审核确认，请确保您已付款成功并在支付时“添加备注”填写了订单流水号，如急需提取，请联系客服人员确认有效。", "SZ0099_MSG_COURSE_PRODUCT_ORDER_NO_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NO_SENT");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_EXPIRED = R.initCode("200015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_EXPIRED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_EXPIRED = R.initMsg("该订单已过期，提取码已失效，如需服务请重新下单。", "SZ0099_MSG_COURSE_PRODUCT_ORDER_EXPIRED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_EXPIRED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_CLOSED = R.initCode("200016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_CLOSED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_CLOSED = R.initMsg("订单已被关闭", "SZ0099_MSG_COURSE_PRODUCT_ORDER_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_CLOSED");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_CANCEL = R.initCode("200017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_CANCEL");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_CANCEL = R.initMsg("订单已被取消", "SZ0099_MSG_COURSE_PRODUCT_ORDER_CANCEL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_CANCEL");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_QUERY_PULLCODE_PASSED = R.initCode("200018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_QUERY_PULLCODE_PASSED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_QUERY_PULLCODE_PASSED = R.initMsg("订单校验通过，可以查看", "SZ0099_MSG_COURSE_PRODUCT_ORDER_QUERY_PULLCODE_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_QUERY_PULLCODE_PASSED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_NULL_EXPIRED = R.initCode("200019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NULL_EXPIRED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_NULL_EXPIRED = R.initMsg("数据非法，该订单过期时间未设定", "SZ0099_MSG_COURSE_PRODUCT_ORDER_NULL_EXPIRED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_NULL_EXPIRED");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_SENT = R.initCode("200020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_SENT");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_SENT = R.initMsg("订单已发货，不能修改", "SZ0099_MSG_COURSE_PRODUCT_ORDER_SENT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_SENT");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_FINISHED = R.initCode("200021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_FINISHED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_FINISHED = R.initMsg("订单已结束", "SZ0099_MSG_COURSE_PRODUCT_ORDER_FINISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_FINISHED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_PASSED = R.initCode("200022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_PASSED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_PASSED = R.initMsg("订单校验通过，可以修改", "SZ0099_MSG_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_PASSED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_SUCCESS = R.initCode("200023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_SUCCESS = R.initMsg("订单Email修改成功", "SZ0099_MSG_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_MODIFY_EMAIL_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_IN_PROCESS = R.initCode("200024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_IN_PROCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_IN_PROCESS = R.initMsg("订单已被处理过", "SZ0099_MSG_COURSE_PRODUCT_ORDER_HAS_IN_PROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_HAS_IN_PROCESS");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_INPROCESS_SUCCESS = R.initCode("200025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_INPROCESS_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_INPROCESS_SUCCESS = R.initMsg("订单已加入处理中", "SZ0099_MSG_COURSE_PRODUCT_ORDER_INPROCESS_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_INPROCESS_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_ORDER_SENT_SUCCESS = R.initCode("200026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_SENT_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_ORDER_SENT_SUCCESS = R.initMsg("订单已发货", "SZ0099_MSG_COURSE_PRODUCT_ORDER_SENT_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_ORDER_SENT_SUCCESS");

	
	
	
	
	
	
	public static final String SZ0099_CODE_COURSE_PRODUCT_NOT_EXIST = R.initCode("210000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PRODUCT_NOT_EXIST = R.initMsg("您要查询的产品不存在", "SZ0099_MSG_COURSE_PRODUCT_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PRODUCT_SHELVED_NO = R.initCode("210001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_SHELVED_NO");
	public static final String SZ0099_MSG_COURSE_PRODUCT_SHELVED_NO = R.initMsg("您要查询的产品已被下架", "SZ0099_MSG_COURSE_PRODUCT_SHELVED_NO", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_SHELVED_NO");

	public static final String SZ0099_CODE_COURSE_PRODUCT_HAS_DELTETED = R.initCode("210002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_HAS_DELTETED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_HAS_DELTETED = R.initMsg("您要查询的产品已被删除", "SZ0099_MSG_COURSE_PRODUCT_HAS_DELTETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_HAS_DELTETED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_DRAFT_EXTRA = R.initCode("210003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_DRAFT_EXTRA");
	public static final String SZ0099_MSG_COURSE_PRODUCT_DRAFT_EXTRA = R.initMsg("先完成以下草稿吧", "SZ0099_MSG_COURSE_PRODUCT_DRAFT_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_DRAFT_EXTRA");

	public static final String SZ0099_CODE_COURSE_PRODUCT_NAME_EMPTY = R.initCode("210004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_NAME_EMPTY = R.initMsg("产品名称不能为空", "SZ0099_MSG_COURSE_PRODUCT_NAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NAME_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_NAME_EXTRA_LENGTH = R.initCode("210005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NAME_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PRODUCT_NAME_EXTRA_LENGTH = R.initMsg("产品名称字符数超长", "SZ0099_MSG_COURSE_PRODUCT_NAME_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NAME_EXTRA_LENGTH");

	public static final String SZ0099_CODE_COURSE_PRODUCT_TITLE_EMPTY = R.initCode("210006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_TITLE_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_TITLE_EMPTY = R.initMsg("产品标题不能为空", "SZ0099_MSG_COURSE_PRODUCT_TITLE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_TITLE_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_TITLE_EXTRA_LENGTH = R.initCode("210007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_TITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PRODUCT_TITLE_EXTRA_LENGTH = R.initMsg("产品标题字符数超长", "SZ0099_MSG_COURSE_PRODUCT_TITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_TITLE_EXTRA_LENGTH");

	public static final String SZ0099_CODE_COURSE_PRODUCT_DESCRIPTION_EMPTY = R.initCode("210008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_DESCRIPTION_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_DESCRIPTION_EMPTY = R.initMsg("产品描述不能为空", "SZ0099_MSG_COURSE_PRODUCT_DESCRIPTION_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_DESCRIPTION_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_DESCRIPTION_EXTRA_LENGTH = R.initCode("210009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_DESCRIPTION_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PRODUCT_DESCRIPTION_EXTRA_LENGTH = R.initMsg("产品描述字符数超长", "SZ0099_MSG_COURSE_PRODUCT_DESCRIPTION_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_DESCRIPTION_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_BASEINFO_SUCCESS = R.initCode("210010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_BASEINFO_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_BASEINFO_SUCCESS = R.initMsg("更新产品基本信息成功", "SZ0099_MSG_COURSE_PRODUCT_MERGE_BASEINFO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_BASEINFO_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_BUY_NOT_EXIST = R.initCode("210011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PRODUCT_BUY_NOT_EXIST = R.initMsg("您要购买的产品不存在", "SZ0099_MSG_COURSE_PRODUCT_BUY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PRODUCT_BUY_SHELVED_NO = R.initCode("210012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_SHELVED_NO");
	public static final String SZ0099_MSG_COURSE_PRODUCT_BUY_SHELVED_NO = R.initMsg("您要购买的产品已被下架", "SZ0099_MSG_COURSE_PRODUCT_BUY_SHELVED_NO", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_SHELVED_NO");

	public static final String SZ0099_CODE_COURSE_PRODUCT_BUY_HAS_DELTETED = R.initCode("210013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_HAS_DELTETED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_BUY_HAS_DELTETED = R.initMsg("您要购买的产品已被删除", "SZ0099_MSG_COURSE_PRODUCT_BUY_HAS_DELTETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_HAS_DELTETED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_BUY_USER_SELF = R.initCode("210014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_USER_SELF");
	public static final String SZ0099_MSG_COURSE_PRODUCT_BUY_USER_SELF = R.initMsg("您不能购买自己发布的产品", "SZ0099_MSG_COURSE_PRODUCT_BUY_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_BUY_USER_SELF");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_NOT_USER_SELF = R.initCode("210015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NOT_USER_SELF");
	public static final String SZ0099_MSG_COURSE_PRODUCT_NOT_USER_SELF = R.initMsg("您无权修改不是自己的产品", "SZ0099_MSG_COURSE_PRODUCT_NOT_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NOT_USER_SELF");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_SHELVED_SUCCESS = R.initCode("210016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_SHELVED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_SHELVED_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_COURSE_PRODUCT_MERGE_SHELVED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_SHELVED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_REFRESH_INVALID = R.initCode("210017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_REFRESH_INVALID");
	public static final String SZ0099_MSG_COURSE_PRODUCT_REFRESH_INVALID = R.initMsg("未超过有效期，不能刷新", "SZ0099_MSG_COURSE_PRODUCT_REFRESH_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_REFRESH_INVALID");

	public static final String SZ0099_CODE_COURSE_PRODUCT_REFRESH_EXTRA = R.initCode("210018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_REFRESH_EXTRA");
	public static final String SZ0099_MSG_COURSE_PRODUCT_REFRESH_EXTRA = R.initMsg("超过365天的产品，不再支持刷新", "SZ0099_MSG_COURSE_PRODUCT_REFRESH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_REFRESH_EXTRA");

	public static final String SZ0099_CODE_COURSE_PRODUCT_REFRESH_SUCCESS = R.initCode("210019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_REFRESH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_REFRESH_SUCCESS = R.initMsg("刷新成功", "SZ0099_MSG_COURSE_PRODUCT_REFRESH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_REFRESH_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_PRICEORI_EMPTY = R.initCode("210020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PRICEORI_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_PRICEORI_EMPTY = R.initMsg("产品原价不能为空", "SZ0099_MSG_COURSE_PRODUCT_PRICEORI_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PRICEORI_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_PRICECUR_EMPTY = R.initCode("210021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PRICECUR_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_PRICECUR_EMPTY = R.initMsg("产品现价不能为空", "SZ0099_MSG_COURSE_PRODUCT_PRICECUR_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PRICECUR_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_STRATEGY_EMPTY = R.initCode("210022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_STRATEGY_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_STRATEGY_EMPTY = R.initMsg("产品优惠策略不能为空", "SZ0099_MSG_COURSE_PRODUCT_STRATEGY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_STRATEGY_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_GRADE_EMPTY = R.initCode("210023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_GRADE_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_GRADE_EMPTY = R.initMsg("产品等级不能为空", "SZ0099_MSG_COURSE_PRODUCT_GRADE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_GRADE_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_RATES_EMPTY = R.initCode("210024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_RATES_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_RATES_EMPTY = R.initMsg("产品最低优惠折扣不能为空", "SZ0099_MSG_COURSE_PRODUCT_RATES_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_RATES_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_RATES_EXTRA = R.initCode("210025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_RATES_EXTRA");
	public static final String SZ0099_MSG_COURSE_PRODUCT_RATES_EXTRA = R.initMsg("产品最低优惠折扣超出设置范围", "SZ0099_MSG_COURSE_PRODUCT_RATES_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_RATES_EXTRA");

	public static final String SZ0099_CODE_COURSE_PRODUCT_GRADE_MORETHAN_9 = R.initCode("210026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_GRADE_MORETHAN_9");
	public static final String SZ0099_MSG_COURSE_PRODUCT_GRADE_MORETHAN_9 = R.initMsg("产品等级大于9时，请与管理员联系", "SZ0099_MSG_COURSE_PRODUCT_GRADE_MORETHAN_9", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_GRADE_MORETHAN_9");

	public static final String SZ0099_CODE_COURSE_PRODUCT_PULL_METHOD_EMPTY = R.initCode("210027", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_METHOD_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_PULL_METHOD_EMPTY = R.initMsg("产品提取方式不能为空", "SZ0099_MSG_COURSE_PRODUCT_PULL_METHOD_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_METHOD_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_LINK_EMPTY = R.initCode("210028", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_LINK_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_LINK_EMPTY = R.initMsg("产品链接不能为空", "SZ0099_MSG_COURSE_PRODUCT_LINK_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_LINK_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_EMPTY = R.initCode("210029", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCT_PULL_CODE_EMPTY = R.initMsg("产品提取密码不能为空", "SZ0099_MSG_COURSE_PRODUCT_PULL_CODE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_EMPTY");

	public static final String SZ0099_CODE_COURSE_PRODUCT_USER_NOT_LOGIN = R.initCode("200030", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_PRODUCT_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后修改", "SZ0099_MSG_COURSE_PRODUCT_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_PRICE_SUCCESS = R.initCode("210031", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_PRICE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_PRICE_SUCCESS = R.initMsg("更新产品价格信息成功", "SZ0099_MSG_COURSE_PRODUCT_MERGE_PRICE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_PRICE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_LENGTH_LESS_4 = R.initCode("210032", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_LENGTH_LESS_4");
	public static final String SZ0099_MSG_COURSE_PRODUCT_PULL_CODE_LENGTH_LESS_4 = R.initMsg("产品提取密码长度不能小于4位", "SZ0099_MSG_COURSE_PRODUCT_PULL_CODE_LENGTH_LESS_4", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_LENGTH_LESS_4");

	public static final String SZ0099_CODE_COURSE_PRODUCT_LINK_LENGTH_MORE_LONG = R.initCode("210033", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_LINK_LENGTH_MORE_LONG");
	public static final String SZ0099_MSG_COURSE_PRODUCT_LINK_LENGTH_MORE_LONG = R.initMsg("下载链接太长了", "SZ0099_MSG_COURSE_PRODUCT_LINK_LENGTH_MORE_LONG", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_LINK_LENGTH_MORE_LONG");

	public static final String SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_LENGTH_TOO_LONG = R.initCode("210034", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_LENGTH_TOO_LONG");
	public static final String SZ0099_MSG_COURSE_PRODUCT_PULL_CODE_LENGTH_TOO_LONG = R.initMsg("产品提取密码长度不能大于10位", "SZ0099_MSG_COURSE_PRODUCT_PULL_CODE_LENGTH_TOO_LONG", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_PULL_CODE_LENGTH_TOO_LONG");

	public static final String SZ0099_CODE_COURSE_PRODUCT_EDIT_QUICKLY_SUCCESS = R.initCode("210035", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_EDIT_QUICKLY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_EDIT_QUICKLY_SUCCESS = R.initMsg("快速编辑保存成功", "SZ0099_MSG_COURSE_PRODUCT_EDIT_QUICKLY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_EDIT_QUICKLY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_PUBLISH_SUCCESS = R.initCode("210036", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_PUBLISH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_PUBLISH_SUCCESS = R.initMsg("产品发布成功", "SZ0099_MSG_COURSE_PRODUCT_MERGE_PUBLISH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_PUBLISH_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_PUBLISHED = R.initCode("210037", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_PUBLISHED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_HAS_PUBLISHED = R.initMsg("产品已发布", "SZ0099_MSG_COURSE_PRODUCT_MERGE_HAS_PUBLISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_PUBLISHED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_CLOSED = R.initCode("210038", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_CLOSED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_HAS_CLOSED = R.initMsg("产品已关闭，若要开启请联系管理员！", "SZ0099_MSG_COURSE_PRODUCT_MERGE_HAS_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_CLOSED");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_CLOSED_SUCCESS = R.initCode("210039", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_CLOSED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_CLOSED_SUCCESS = R.initMsg("产品关闭成功", "SZ0099_MSG_COURSE_PRODUCT_MERGE_CLOSED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_CLOSED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_NOT_PUBLISH = R.initCode("210040", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NOT_PUBLISH");
	public static final String SZ0099_MSG_COURSE_PRODUCT_NOT_PUBLISH = R.initMsg("产品尚未发布", "SZ0099_MSG_COURSE_PRODUCT_NOT_PUBLISH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_NOT_PUBLISH");

	
	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_PRODUCT_USERID_NULL = R.initCode("210041", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PRODUCT_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_PRODUCT_USERID_NULL = R.initMsg("产品用户id为空，非法产品，禁止编辑", "SZ0099_MSG_COURSE_PARAGRAGH_PRODUCT_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PRODUCT_USERID_NULL");
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL = R.initCode("210042", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_USERID_NULL = R.initMsg("还没登录，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_NULL");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT = R.initCode("210043", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_USERID_CONFLICT = R.initMsg("非本人发布的产品，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_USERID_CONFLICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_USERID_CONFLICT");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA = R.initCode("210044", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_TOTAL_EXTRA = R.initMsg("段落总数超限，请减少后再增加", "SZ0099_MSG_COURSE_PARAGRAGH_TOTAL_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_TOTAL_EXTRA");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST = R.initCode("210045", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_NOT_EXIST = R.initMsg("段落不存在", "SZ0099_MSG_COURSE_PARAGRAGH_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_NOT_EXIST");

	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS = R.initCode("210046", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_MERGE_SUCCESS = R.initMsg("段落保存成功", "SZ0099_MSG_COURSE_PARAGRAGH_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_MERGE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST = R.initCode("210046", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST = R.initMsg("段落上传数据不存在", "SZ0099_MSG_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_UPLOAD_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS = R.initCode("210047", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_DELETE_SUCCESS = R.initMsg("段落删除成功", "SZ0099_MSG_COURSE_PARAGRAGH_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS = R.initCode("210048", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_ADD_SUCCESS = R.initMsg("段落添加成功", "SZ0099_MSG_COURSE_PARAGRAGH_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS = R.initCode("210049", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS = R.initMsg("已全部删除，成功", "SZ0099_MSG_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_DELETE_ALL_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_DELERED_SUCCESS = R.initCode("210058", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_DELERED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_DELERED_SUCCESS = R.initMsg("产品删除成功", "SZ0099_MSG_COURSE_PRODUCT_MERGE_DELERED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_DELERED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_DELERED = R.initCode("210059", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_DELERED");
	public static final String SZ0099_MSG_COURSE_PRODUCT_MERGE_HAS_DELERED = R.initMsg("产品已被删除！", "SZ0099_MSG_COURSE_PRODUCT_MERGE_HAS_DELERED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_MERGE_HAS_DELERED");

	
	
	
	
	public static final String SZ0099_CODE_COURSE_TAG_ADD_SUCCESS = R.initCode("211001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_TAG_ADD_SUCCESS = R.initMsg("标签添加成功", "SZ0099_MSG_COURSE_TAG_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_TAG_EMPTY = R.initCode("211002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_EMPTY = R.initMsg("标签不能为空", "SZ0099_MSG_COURSE_TAG_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_NAME_EMPTY = R.initCode("211003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_NAME_EMPTY = R.initMsg("标签名称不能为空", "SZ0099_MSG_COURSE_TAG_NAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NAME_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_PRODUCT_TAG_EXIST = R.initCode("211004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_TAG_EXIST");
	public static final String SZ0099_MSG_COURSE_PRODUCT_TAG_EXIST = R.initMsg("产品标签已存在", "SZ0099_MSG_COURSE_PRODUCT_TAG_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCT_TAG_EXIST");

	public static final String SZ0099_CODE_COURSE_PRODUCTID_EMPTY = R.initCode("211005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCTID_EMPTY");
	public static final String SZ0099_MSG_COURSE_PRODUCTID_EMPTY = R.initMsg("添加标签时，产品ID不能为空", "SZ0099_MSG_COURSE_PRODUCTID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PRODUCTID_EMPTY");

	public static final String SZ0099_CODE_COURSE_PTAGID_EMPTY = R.initCode("211006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PTAGID_EMPTY");
	public static final String SZ0099_MSG_COURSE_PTAGID_EMPTY = R.initMsg("删除标签时，ID不能为空", "SZ0099_MSG_COURSE_PTAGID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PTAGID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAGID_EMPTY = R.initCode("211007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAGID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAGID_EMPTY = R.initMsg("删除标签时，标签ID不能为空", "SZ0099_MSG_COURSE_TAGID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAGID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_DELETE_SUCCESS = R.initCode("211008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_TAG_DELETE_SUCCESS = R.initMsg("标签删除成功", "SZ0099_MSG_COURSE_TAG_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_DELETE_PRODUCTID_EMPTY = R.initCode("211009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_DELETE_PRODUCTID_EMPTY");
	public static final String SZ0099_MSG_COURSE_DELETE_PRODUCTID_EMPTY = R.initMsg("删除标签时，产品ID不能为空", "SZ0099_MSG_COURSE_DELETE_PRODUCTID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_DELETE_PRODUCTID_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_TAG_NUM_EXTRS = R.initCode("211010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NUM_EXTRS");
	public static final String SZ0099_MSG_COURSE_TAG_NUM_EXTRS = R.initMsg("标签数量已超限", "SZ0099_MSG_COURSE_TAG_NUM_EXTRS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NUM_EXTRS");

	public static final String SZ0099_CODE_COURSE_TAG_NAME_LENGTH_EXTRA = R.initCode("211011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NAME_LENGTH_EXTRA");
	public static final String SZ0099_MSG_COURSE_TAG_NAME_LENGTH_EXTRA = R.initMsg("标签名称超长了", "SZ0099_MSG_COURSE_TAG_NAME_LENGTH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NAME_LENGTH_EXTRA");

	
	
	//------------------------------
	
	public static final String SZ0099_CODE_COURSE_USER_EMAIL_EXISTS = R.initCode("212000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_EXISTS");
	public static final String SZ0099_MSG_COURSE_USER_EMAIL_EXISTS = R.initMsg("Email已存在", "SZ0099_MSG_COURSE_USER_EMAIL_EXISTS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_EXISTS");

	public static final String SZ0099_CODE_COURSE_USER_EMAIL_MODIFY_SUCCESS = R.initCode("212001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_EMAIL_MODIFY_SUCCESS = R.initMsg("Email修改成功", "SZ0099_MSG_COURSE_USER_EMAIL_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_MOBILE_MODIFY_SUCCESS = R.initCode("212002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_MOBILE_MODIFY_SUCCESS = R.initMsg("手机号修改成功", "SZ0099_MSG_COURSE_USER_MOBILE_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_EMPTY = R.initCode("212003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_EMPTY = R.initMsg("身份证号码不能为空", "SZ0099_MSG_COURSE_USER_IDENTITY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EMPTY");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_INVALID = R.initCode("212004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_INVALID");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_INVALID = R.initMsg("身份证号码不合法！", "SZ0099_MSG_COURSE_USER_IDENTITY_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_INVALID");

	public static final String SZ0099_CODE_COURSE_USERID_EMPTY = R.initCode("212005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USERID_EMPTY");
	public static final String SZ0099_MSG_COURSE_USERID_EMPTY = R.initMsg("用户未登录，请登录后重试！", "SZ0099_MSG_COURSE_USERID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USERID_EMPTY");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_VERIFY_SUCCESS = R.initCode("212006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_VERIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_VERIFY_SUCCESS = R.initMsg("用户身份证认证提交成功，请耐心等待工作人员审核", "SZ0099_MSG_COURSE_USER_IDENTITY_VERIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_VERIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_NOT_EXIST = R.initCode("212006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_USER_NOT_EXIST = R.initMsg("用户不存在", "SZ0099_MSG_COURSE_USER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_USER_ID_INVALID = R.initCode("212007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_ID_INVALID");
	public static final String SZ0099_MSG_COURSE_USER_ID_INVALID = R.initMsg("用户ID不合法", "SZ0099_MSG_COURSE_USER_ID_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_ID_INVALID");

	public static final String SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_INPROCESS = R.initCode("212008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_INPROCESS");
	public static final String SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_INPROCESS= R.initMsg("已在审核中", "SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_INPROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_INPROCESS");

	public static final String SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_PASSED = R.initCode("212009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_PASSED");
	public static final String SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_PASSED= R.initMsg("已审核通过", "SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_PASSED");

	public static final String SZ0099_CODE_COURSE_USER_IDVERIFY_FACE_EMPTY = R.initCode("212010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_FACE_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_IDVERIFY_FACE_EMPTY= R.initMsg("身份证照片未上传", "SZ0099_MSG_COURSE_USER_IDVERIFY_FACE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_FACE_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_USER_NICKNAME_EMPTY = R.initCode("212011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_NICKNAME_EMPTY= R.initMsg("昵称不能为空", "SZ0099_MSG_COURSE_USER_NICKNAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_EMPTY");

	public static final String SZ0099_CODE_COURSE_USER_NICKNAME_MODIFY_SUCCESS = R.initCode("212012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_NICKNAME_MODIFY_SUCCESS = R.initMsg("昵称修改成功", "SZ0099_MSG_COURSE_USER_NICKNAME_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_EXISTS = R.initCode("212013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EXISTS");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_EXISTS = R.initMsg("身份证号码已存在", "SZ0099_MSG_COURSE_USER_IDENTITY_EXISTS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EXISTS");

	public static final String SZ0099_CODE_COURSE_USER_MOBILE_EXISTS = R.initCode("212014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_EXISTS");
	public static final String SZ0099_MSG_COURSE_USER_MOBILE_EXISTS = R.initMsg("手机号码已存在", "SZ0099_MSG_COURSE_USER_MOBILE_EXISTS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_EXISTS");

	
	public static final String SZ0099_CODE_COURSE_USER_SAYWORD_MODIFY_SUCCESS = R.initCode("212015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_SAYWORD_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_SAYWORD_MODIFY_SUCCESS = R.initMsg("传说修改成功", "SZ0099_MSG_COURSE_USER_SAYWORD_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_SAYWORD_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_SAYWORD_EMPTY = R.initCode("212016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_SAYWORD_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_SAYWORD_EMPTY = R.initMsg("传说不能为空", "SZ0099_MSG_COURSE_USER_SAYWORD_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_SAYWORD_EMPTY");

	
	
	public static final String SZ0099_CODE_COURSE_USER_POSTNAME_MODIFY_SUCCESS = R.initCode("212017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_POSTNAME_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_POSTNAME_MODIFY_SUCCESS = R.initMsg("联系人名称修改成功", "SZ0099_MSG_COURSE_USER_POSTNAME_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_POSTNAME_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_POSTNAME_EMPTY = R.initCode("212018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_POSTNAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_POSTNAME_EMPTY = R.initMsg("联系人名称不能为空", "SZ0099_MSG_COURSE_USER_POSTNAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_POSTNAME_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_USER_REALNAME_MODIFY_SUCCESS = R.initCode("212019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_REALNAME_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_REALNAME_MODIFY_SUCCESS = R.initMsg("真实姓名修改成功", "SZ0099_MSG_COURSE_USER_REALNAME_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_REALNAME_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_REALNAME_EMPTY = R.initCode("212020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_REALNAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_REALNAME_EMPTY = R.initMsg("真实姓名不能为空", "SZ0099_MSG_COURSE_USER_REALNAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_REALNAME_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_USER_PRIVATE_SETTING_ONLY1OR0 = R.initCode("212021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_PRIVATE_SETTING_ONLY1OR0");
	public static final String SZ0099_MSG_COURSE_USER_PRIVATE_SETTING_ONLY1OR0 = R.initMsg("隐私信息只允许设置【显示or隐藏】", "SZ0099_MSG_COURSE_USER_PRIVATE_SETTING_ONLY1OR0", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_PRIVATE_SETTING_ONLY1OR0");

	public static final String SZ0099_CODE_COURSE_USER_PRIVATE_SETTING_SUCCESS = R.initCode("212022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_PRIVATE_SETTING_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_PRIVATE_SETTING_SUCCESS = R.initMsg("隐私设置成功", "SZ0099_MSG_COURSE_USER_PRIVATE_SETTING_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_PRIVATE_SETTING_SUCCESS");

	public static final String SZ0099_CODE_OOD_USER_VERIFY_ID_EMPTY = R.initCode("212023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_ID_EMPTY");
	public static final String SZ0099_MSG_OOD_USER_VERIFY_ID_EMPTY = R.initMsg("认证ID不能为空", "SZ0099_MSG_OOD_USER_VERIFY_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_ID_EMPTY");

	public static final String SZ0099_CODE_OOD_USER_VERIFY_EMPTY = R.initCode("212024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_EMPTY");
	public static final String SZ0099_MSG_OOD_USER_VERIFY_EMPTY = R.initMsg("认证信息不存在", "SZ0099_MSG_OOD_USER_VERIFY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_EMPTY");

	public static final String SZ0099_CODE_OOD_USER_VERIFY_REMARK_BLANK = R.initCode("212025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_REMARK_BLANK");
	public static final String SZ0099_MSG_OOD_USER_VERIFY_REMARK_BLANK = R.initMsg("驳回原因不能为空", "SZ0099_MSG_OOD_USER_VERIFY_REMARK_BLANK", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_REMARK_BLANK");

	public static final String SZ0099_CODE_OOD_USER_VERIFY_REJECT = R.initCode("212026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_REJECT");
	public static final String SZ0099_MSG_OOD_USER_VERIFY_REJECT = R.initMsg("身份认证已驳回", "SZ0099_MSG_OOD_USER_VERIFY_REJECT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_VERIFY_REJECT");

	//----用户申领成为领队
	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_SUCCESS = R.initCode("213000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_SUCCESS");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_SUCCESS = R.initMsg("申请领队提交成功", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_SUCCESS");

	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFING = R.initCode("213001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFING");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_VERIFING = R.initMsg("申请领队审核中", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_VERIFING", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFING");

	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFIED = R.initCode("213002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFIED");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_VERIFIED = R.initMsg("申请领队审核已通过", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_VERIFIED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFIED");

	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFIED_NOT = R.initCode("213003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFIED_NOT");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_VERIFIED_NOT = R.initMsg("申请领队审核未通过", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_VERIFIED_NOT", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_VERIFIED_NOT");

	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_NUM_NOT_ENOUGH = R.initCode("213004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_NUM_NOT_ENOUGH");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_NUM_NOT_ENOUGH = R.initMsg("申请领队文章数量不够", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_NUM_NOT_ENOUGH", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_NUM_NOT_ENOUGH");

	
	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_USER_NOT_EXIST = R.initCode("213005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_USER_NOT_EXIST");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_USER_NOT_EXIST = R.initMsg("用户信息不存在", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_USER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_USER_NOT_EXIST");

	
	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_IDSTATUS_NOT_VERIFIED = R.initCode("213006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_IDSTATUS_NOT_VERIFIED");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_IDSTATUS_NOT_VERIFIED = R.initMsg("用户尚未进行身份认证", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_IDSTATUS_NOT_VERIFIED", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_IDSTATUS_NOT_VERIFIED");

	public static final String SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_MOBILE_NOT_BIND = R.initCode("213007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_MOBILE_NOT_BIND");
	public static final String SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_MOBILE_NOT_BIND = R.initMsg("用户尚未绑定手机号", "SZ0099_MSG_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_MOBILE_NOT_BIND", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_USER_APPLY_CLUB_LEADER_ARTICLE_MOBILE_NOT_BIND");

	//------------------
	
	
	public static final String SZ0099_CODE_COURSE_PERSONAL_PROFESSION_EXTRA = R.initCode("230003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_PROFESSION_EXTRA");
	public static final String SZ0099_MSG_COURSE_PERSONAL_PROFESSION_EXTRA = R.initMsg("技能数已经满了", "SZ0099_MSG_COURSE_PERSONAL_PROFESSION_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_PROFESSION_EXTRA");

	public static final String SZ0099_CODE_COURSE_PERSONAL_PROFESSION_NOT_EXIST = R.initCode("230004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_PROFESSION_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_PERSONAL_PROFESSION_NOT_EXIST = R.initMsg("您要查询的技能不存在", "SZ0099_MSG_COURSE_PERSONAL_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PERSONAL_PROFESSION_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_PROFESSION_USERID_NULL = R.initCode("230005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_PROFESSION_USERID_NULL");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_PERSONAL_PROFESSION_USERID_NULL = R.initMsg("用户id为空，非法技能，禁止修炼", "SZ0099_MSG_COURSE_PARAGRAGH_PERSONAL_PROFESSION_USERID_NULL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PERSONAL_PROFESSION_USERID_NULL");

	public static final String SZ0099_CODE_COURSE_PARAGRAGH_PROFESSION_USERID_CONFLICT = R.initCode("230006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PROFESSION_USERID_CONFLICT");
	public static final String SZ0099_MSG_COURSE_PARAGRAGH_PROFESSION_USERID_CONFLICT = R.initMsg("非本人技能，不能编辑", "SZ0099_MSG_COURSE_PARAGRAGH_PROFESSION_USERID_CONFLICT", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PARAGRAGH_PROFESSION_USERID_CONFLICT");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_DELERED = R.initCode("230007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_DELERED");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_HAS_DELERED = R.initMsg("技能已被删除！", "SZ0099_MSG_COURSE_PROFESSION_MERGE_HAS_DELERED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_DELERED");

	public static final String SZ0099_CODE_COURSE_PROFESSION_NAME_EXTRA_LENGTH = R.initCode("230008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NAME_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PROFESSION_NAME_EXTRA_LENGTH = R.initMsg("技能名称字符数超长", "SZ0099_MSG_COURSE_PROFESSION_NAME_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NAME_EXTRA_LENGTH");

	public static final String SZ0099_CODE_COURSE_PROFESSION_NAME_EMPTY = R.initCode("230009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_NAME_EMPTY = R.initMsg("技能名称不能为空", "SZ0099_MSG_COURSE_PROFESSION_NAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NAME_EMPTY");

	public static final String SZ0099_CODE_COURSE_PROFESSION_TITLE_EMPTY = R.initCode("230010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_TITLE_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_TITLE_EMPTY = R.initMsg("技能标题不能为空", "SZ0099_MSG_COURSE_PROFESSION_TITLE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_TITLE_EMPTY");

	public static final String SZ0099_CODE_COURSE_PROFESSION_TITLE_EXTRA_LENGTH = R.initCode("230011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_TITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PROFESSION_TITLE_EXTRA_LENGTH = R.initMsg("技能标题字符数超长", "SZ0099_MSG_COURSE_PROFESSION_TITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_TITLE_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_COURSE_PROFESSION_DESCRIPTION_EMPTY = R.initCode("230012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DESCRIPTION_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_DESCRIPTION_EMPTY = R.initMsg("技能描述不能为空", "SZ0099_MSG_COURSE_PROFESSION_DESCRIPTION_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DESCRIPTION_EMPTY");

	public static final String SZ0099_CODE_COURSE_PROFESSION_DESCRIPTION_EXTRA_LENGTH = R.initCode("230013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DESCRIPTION_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PROFESSION_DESCRIPTION_EXTRA_LENGTH = R.initMsg("技能描述字符数超长", "SZ0099_MSG_COURSE_PROFESSION_DESCRIPTION_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DESCRIPTION_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_BASEINFO_SUCCESS = R.initCode("230014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_BASEINFO_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_BASEINFO_SUCCESS = R.initMsg("更新技能基本信息成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_BASEINFO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_BASEINFO_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_PUBLISH_SUCCESS = R.initCode("230015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_PUBLISH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_PUBLISH_SUCCESS = R.initMsg("技能发布成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_PUBLISH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_PUBLISH_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_PUBLISHED = R.initCode("230016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_PUBLISHED");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_HAS_PUBLISHED = R.initMsg("技能已发布", "SZ0099_MSG_COURSE_PROFESSION_MERGE_HAS_PUBLISHED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_PUBLISHED");

	public static final String SZ0099_CODE_COURSE_PROFESSION_EDIT_QUICKLY_SUCCESS = R.initCode("230017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EDIT_QUICKLY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_EDIT_QUICKLY_SUCCESS = R.initMsg("快速编辑保存成功", "SZ0099_MSG_COURSE_PROFESSION_EDIT_QUICKLY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EDIT_QUICKLY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_CLOSED_SUCCESS = R.initCode("230018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_CLOSED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_CLOSED_SUCCESS = R.initMsg("技能关闭成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_CLOSED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_CLOSED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_CLOSED = R.initCode("230019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_CLOSED");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_HAS_CLOSED = R.initMsg("技能已关闭，若要开启请联系管理员！", "SZ0099_MSG_COURSE_PROFESSION_MERGE_HAS_CLOSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_HAS_CLOSED");

	public static final String SZ0099_CODE_COURSE_PROFESSION_NOT_USER_SELF = R.initCode("230020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NOT_USER_SELF");
	public static final String SZ0099_MSG_COURSE_PROFESSION_NOT_USER_SELF = R.initMsg("您无权修改不是自己的技能", "SZ0099_MSG_COURSE_PROFESSION_NOT_USER_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NOT_USER_SELF");

	public static final String SZ0099_CODE_COURSE_PROFESSION_REFRESH_INVALID = R.initCode("230021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REFRESH_INVALID");
	public static final String SZ0099_MSG_COURSE_PROFESSION_REFRESH_INVALID = R.initMsg("未超过有效期，不能刷新", "SZ0099_MSG_COURSE_PROFESSION_REFRESH_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REFRESH_INVALID");

	public static final String SZ0099_CODE_COURSE_PROFESSION_REFRESH_EXTRA = R.initCode("230022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REFRESH_EXTRA");
	public static final String SZ0099_MSG_COURSE_PROFESSION_REFRESH_EXTRA = R.initMsg("超过365天的技能，不再支持刷新", "SZ0099_MSG_COURSE_PROFESSION_REFRESH_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REFRESH_EXTRA");

	public static final String SZ0099_CODE_COURSE_PROFESSION_SUBTITLE_EXTRA_LENGTH = R.initCode("230023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_SUBTITLE_EXTRA_LENGTH");
	public static final String SZ0099_MSG_COURSE_PROFESSION_SUBTITLE_EXTRA_LENGTH = R.initMsg("技能子标题字符数超长", "SZ0099_MSG_COURSE_PROFESSION_SUBTITLE_EXTRA_LENGTH", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_SUBTITLE_EXTRA_LENGTH");

	
	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_UNPUBLISHED_SUCCESS = R.initCode("230024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_UNPUBLISHED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_UNPUBLISHED_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_UNPUBLISHED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_UNPUBLISHED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_DELERED_SUCCESS = R.initCode("230025", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_DELERED_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_DELERED_SUCCESS = R.initMsg("技能删除成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_DELERED_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_DELERED_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_NOT_LOGIN = R.initCode("230026", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_PROFESSION_NOT_LOGIN = R.initMsg("登录状态已失效，请重新登录后查看", "SZ0099_MSG_COURSE_PROFESSION_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_PROFESSION_FIND_MAINCIRCLE_SUCCESS = R.initCode("230027", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FIND_MAINCIRCLE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_FIND_MAINCIRCLE_SUCCESS = R.initMsg("查询圆形菜单成功", "SZ0099_MSG_COURSE_PROFESSION_FIND_MAINCIRCLE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FIND_MAINCIRCLE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_USERID_EMPTY = R.initCode("230028", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_USERID_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_USERID_EMPTY = R.initMsg("数据非法，用户id为空", "SZ0099_MSG_COURSE_PROFESSION_USERID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_USERID_EMPTY");

	public static final String SZ0099_CODE_COURSE_PROFESSION_USER_EMPTY = R.initCode("230029", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_USER_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_USER_EMPTY = R.initMsg("数据非法，查询的用户为空", "SZ0099_MSG_COURSE_PROFESSION_USER_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_USER_EMPTY");

	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_MAINTYPE_SUCCESS = R.initCode("230030", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_MAINTYPE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_MAINTYPE_SUCCESS = R.initMsg("主技能设置成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_MAINTYPE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_MAINTYPE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_VIEW_DETAIL_SUCCESS = R.initCode("230031", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_VIEW_DETAIL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_VIEW_DETAIL_SUCCESS = R.initMsg("查询技能详情成功", "SZ0099_MSG_COURSE_PROFESSION_VIEW_DETAIL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_VIEW_DETAIL_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_PRAISE_PAGE_SUCCESS = R.initCode("230032", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_PAGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_PRAISE_PAGE_SUCCESS = R.initMsg("查询点赞技能列表成功", "SZ0099_MSG_COURSE_PROFESSION_PRAISE_PAGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_PAGE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_PROFESSION_COVER_EMPTY = R.initCode("230033", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_COVER_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_COVER_EMPTY = R.initMsg("技能封面图未上传", "SZ0099_MSG_COURSE_PROFESSION_COVER_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_COVER_EMPTY");

	public static final String SZ0099_CODE_COURSE_PROFESSION_CATEGORY_EMPTY = R.initCode("230034", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_CATEGORY_EMPTY");
	public static final String SZ0099_MSG_COURSE_PROFESSION_CATEGORY_EMPTY = R.initMsg("技能还没选择分类", "SZ0099_MSG_COURSE_PROFESSION_CATEGORY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_CATEGORY_EMPTY");

	
	
	public static final String SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_SUCCESS = R.initCode("230035", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_SUCCESS");
	public static final String SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_SUCCESS = R.initMsg("操作成功", "SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_SUCCESS");

	public static final String SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_EMPLTY = R.initCode("230036", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_EMPLTY");
	public static final String SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_EMPLTY = R.initMsg("用户id为空，请登录再试", "SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_EMPLTY");

	public static final String SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_EMPLTY = R.initCode("230037", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_EMPLTY");
	public static final String SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_EMPLTY = R.initMsg("此操作id不能为空", "SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_EMPLTY");

	public static final String SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY = R.initCode("230038", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY");
	public static final String SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY = R.initMsg("查无此实体", "SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_ID_ENTITY_EMPLTY");

	public static final String SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_INVALID = R.initCode("230039", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_INVALID");
	public static final String SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_INVALID = R.initMsg("非法操作用户", "SZ0099_MSG_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PARAGRAGH_PHOTO_USERID_INVALID");

	
	public static final String SZ0099_CODE_OOD_PROFESSION_PHOTO_MAINID_EMPLTY = R.initCode("230040", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PHOTO_MAINID_EMPLTY");
	public static final String SZ0099_MSG_OOD_PROFESSION_PHOTO_MAINID_EMPLTY = R.initMsg("所绑定的文章ID为空", "SZ0099_MSG_OOD_PROFESSION_PHOTO_MAINID_EMPLTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PHOTO_MAINID_EMPLTY");

	public static final String SZ0099_CODE_OOD_PROFESSION_PHOTO_MAINNUM_EXTRA = R.initCode("230041", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PHOTO_MAINNUM_EXTRA");
	public static final String SZ0099_MSG_OOD_PROFESSION_PHOTO_MAINNUM_EXTRA = R.initMsg("图片数量超限", "SZ0099_MSG_OOD_PROFESSION_PHOTO_MAINNUM_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_PHOTO_MAINNUM_EXTRA");

	
	
	public static final String SZ0099_CODE_OOD_PROFESSION_MERGE_TITLE_SUCCESS = R.initCode("230042", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_MERGE_TITLE_SUCCESS");
	public static final String SZ0099_MSG_OOD_PROFESSION_MERGE_TITLE_SUCCESS = R.initMsg("更新技能标题成功", "SZ0099_MSG_OOD_PROFESSION_MERGE_TITLE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_MERGE_TITLE_SUCCESS");

	public static final String SZ0099_CODE_OOD_PROFESSION_MERGE_DESCRPTION_SUCCESS = R.initCode("230043", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_MERGE_DESCRPTION_SUCCESS");
	public static final String SZ0099_MSG_OOD_PROFESSION_MERGE_DESCRPTION_SUCCESS = R.initMsg("更新技能概要成功", "SZ0099_MSG_OOD_PROFESSION_MERGE_DESCRPTION_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_OOD_PROFESSION_MERGE_DESCRPTION_SUCCESS");

	
	
	
	
	public static final String SZ0099_CODE_COURSE_PROFESSION_TAG_EXIST = R.initCode("231004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_TAG_EXIST");
	public static final String SZ0099_MSG_COURSE_PROFESSION_TAG_EXIST = R.initMsg("技能标签已存在", "SZ0099_MSG_COURSE_PROFESSION_TAG_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_TAG_EXIST");

	public static final String SZ0099_CODE_COURSE_TAG_PROFESSIONID_EMPTY = R.initCode("231005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_PROFESSIONID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_PROFESSIONID_EMPTY = R.initMsg("添加标签时，技能ID不能为空", "SZ0099_MSG_COURSE_TAG_PROFESSIONID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_PROFESSIONID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_DELETE_PROFESSIONID_EMPTY = R.initCode("231009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_PROFESSIONID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_DELETE_PROFESSIONID_EMPTY = R.initMsg("删除标签时，技能ID不能为空", "SZ0099_MSG_COURSE_TAG_DELETE_PROFESSIONID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_PROFESSIONID_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_PRAISE_SUCCESS = R.initCode("232059", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_PRAISE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_PRAISE_SUCCESS = R.initMsg("技能点赞成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_PRAISE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_PRAISE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_PRAISE_USER_NOT_LOGIN = R.initCode("232060", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_PROFESSION_PRAISE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后点赞", "SZ0099_MSG_COURSE_PROFESSION_PRAISE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_PROFESSION_PRAISE_EXIST = R.initCode("232061", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_EXIST");
	public static final String SZ0099_MSG_COURSE_PROFESSION_PRAISE_EXIST = R.initMsg("你已经点过赞了", "SZ0099_MSG_COURSE_PROFESSION_PRAISE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_EXIST");

	public static final String SZ0099_CODE_COURSE_PROFESSION_PRAISE_USER_SELF_NOALLOW = R.initCode("232062", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_USER_SELF_NOALLOW");
	public static final String SZ0099_MSG_COURSE_PROFESSION_PRAISE_USER_SELF_NOALLOW = R.initMsg("自己赞自己？还是让别人来点赞吧！", "SZ0099_MSG_COURSE_PROFESSION_PRAISE_USER_SELF_NOALLOW", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_PRAISE_USER_SELF_NOALLOW");
	
	
	
	public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_FAVIRATE_SUCCESS = R.initCode("232063", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_FAVIRATE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_FAVIRATE_SUCCESS = R.initMsg("技能收藏成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_FAVIRATE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_FAVIRATE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_USER_NOT_LOGIN = R.initCode("232064", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_PROFESSION_FAVIRATE_USER_NOT_LOGIN = R.initMsg("您还没有登录，请登录后点赞", "SZ0099_MSG_COURSE_PROFESSION_FAVIRATE_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_EXIST = R.initCode("232065", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_EXIST");
	public static final String SZ0099_MSG_COURSE_PROFESSION_FAVIRATE_EXIST = R.initMsg("你已经收藏过了", "SZ0099_MSG_COURSE_PROFESSION_FAVIRATE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_EXIST");

	public static final String SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_USER_SELF_NOALLOW = R.initCode("232066", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_USER_SELF_NOALLOW");
	public static final String SZ0099_MSG_COURSE_PROFESSION_FAVIRATE_USER_SELF_NOALLOW = R.initMsg("自己的也收藏？让别人收藏吧！", "SZ0099_MSG_COURSE_PROFESSION_FAVIRATE_USER_SELF_NOALLOW", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_FAVIRATE_USER_SELF_NOALLOW");
	
	
	//技能绑定文章begin
		public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_BIND_SUCCESS = R.initCode("241000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_BIND_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_BIND_SUCCESS = R.initMsg("技能绑定成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_BIND_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_BIND_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_QUERY_LIST_SUCCESS = R.initCode("241001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_QUERY_LIST_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_QUERY_LIST_SUCCESS = R.initMsg("查询技能列表", "SZ0099_MSG_COURSE_PROFESSION_QUERY_LIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_QUERY_LIST_SUCCESS");

		
		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_SAVE_SUCCESS = R.initCode("240000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_SAVE_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_SAVE_SUCCESS = R.initMsg("项目位置保存成功", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_SAVE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_SAVE_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_PERSIST_SUCCESS = R.initCode("240001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_PERSIST_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_PERSIST_SUCCESS = R.initMsg("项目位置创建成功", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_PERSIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_PERSIST_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_EXTRA = R.initCode("240002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_EXTRA");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_VARIETY_EXTRA = R.initMsg("品种数超限，请联系开发者", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_VARIETY_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_EXTRA");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_USER_NOT_LOGIN = R.initCode("240003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_USER_NOT_LOGIN");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_USER_NOT_LOGIN = R.initMsg("还没登录，请登录后操作", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_USER_NOT_LOGIN");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_EXIST = R.initCode("240004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_EXIST");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_VARIETY_EXIST = R.initMsg("项目品种已存在", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_VARIETY_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_EXIST");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_SELF = R.initCode("240005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_SELF");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_NOT_SELF = R.initMsg("无权编辑此项目品种", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_SELF");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_NOT_EXIST = R.initCode("240006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_NOT_EXIST");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_VARIETY_NOT_EXIST = R.initMsg("项目品种不存在", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_VARIETY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_VARIETY_NOT_EXIST");

		
		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_HAS_POSITION = R.initCode("240007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_HAS_POSITION");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_HAS_POSITION = R.initMsg("项目品种下还有位置，不可删除", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_HAS_POSITION", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_HAS_POSITION");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_DELETE_SUCCESS = R.initCode("240008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_DELETE_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_DELETE_SUCCESS = R.initMsg("项目品种删除成功", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_DELETE_SUCCESS");

		
		//public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_SELF = R.initCode("240005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_SELF");
		//public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_NOT_SELF = R.initMsg("无权编辑此项目品种", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_SELF");

		
		public static final String SZ0099_CODE_COURSE_PROFESSION_ADD_SUCCESS = R.initCode("240106", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_ADD_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_ADD_SUCCESS = R.initMsg("技能添加成功", "SZ0099_MSG_COURSE_PROFESSION_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_ADD_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_EXIST = R.initCode("240107", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_EXIST");
		public static final String SZ0099_MSG_COURSE_PROFESSION_EXTEND_NOT_EXIST = R.initMsg("技能信息不存在", "SZ0099_MSG_COURSE_PROFESSION_EXTEND_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_EXTEND_NOT_EXIST");

		public static final String SZ0099_CODE_COURSE_PROFESSION_CODE_EXIST = R.initCode("240108", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_CODE_EXIST");
		public static final String SZ0099_MSG_COURSE_PROFESSION_CODE_EXIST = R.initMsg("技能code已存在", "SZ0099_MSG_COURSE_PROFESSION_CODE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_CODE_EXIST");

		public static final String SZ0099_CODE_COURSE_PROFESSION_MAINID_EMPTY = R.initCode("240109", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MAINID_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_MAINID_EMPTY = R.initMsg("mainId不能为空", "SZ0099_MSG_COURSE_PROFESSION_MAINID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MAINID_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_SUBID_EMPTY = R.initCode("240110", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_SUBID_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_SUBID_EMPTY = R.initMsg("subId不能为空", "SZ0099_MSG_COURSE_PROFESSION_SUBID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_SUBID_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_MERGE_SUCCESS = R.initCode("240111", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_MERGE_SUCCESS = R.initMsg("技能保存成功", "SZ0099_MSG_COURSE_PROFESSION_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_MERGE_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_NOT_EXIST = R.initCode("240112", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NOT_EXIST");
		public static final String SZ0099_MSG_COURSE_PROFESSION_NOT_EXIST = R.initMsg("技能id不存在", "SZ0099_MSG_COURSE_PROFESSION_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_NOT_EXIST");

		public static final String SZ0099_CODE_COURSE_PROFESSION_HAS_CHILDREN = R.initCode("240113", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_HAS_CHILDREN");
		public static final String SZ0099_MSG_COURSE_PROFESSION_HAS_CHILDREN = R.initMsg("该技能下面还有子类", "SZ0099_MSG_COURSE_PROFESSION_HAS_CHILDREN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_HAS_CHILDREN");

		public static final String SZ0099_CODE_COURSE_PROFESSION_DELETE_SUCCESS = R.initCode("240114", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DELETE_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_DELETE_SUCCESS = R.initMsg("技能删除成功", "SZ0099_MSG_COURSE_PROFESSION_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DELETE_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_HAS_REF = R.initCode("240115", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_HAS_REF");
		public static final String SZ0099_MSG_COURSE_PROFESSION_HAS_REF = R.initMsg("该技能下面关联有产品", "SZ0099_MSG_COURSE_PROFESSION_HAS_REF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_HAS_REF");

		public static final String SZ0099_CODE_COURSE_PROFESSION_DELETE_ALL_SUCCESS = R.initCode("240116", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DELETE_ALL_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_DELETE_ALL_SUCCESS = R.initMsg("已全部删除，成功", "SZ0099_MSG_COURSE_PROFESSION_DELETE_ALL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_DELETE_ALL_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REFRESH_SUCCESS = R.initCode("240117", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REFRESH_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REFRESH_SUCCESS = R.initMsg("技能刷新成功", "SZ0099_MSG_COURSE_PROFESSION_REFRESH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REFRESH_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_HAS_BIND = R.initCode("240118", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_HAS_BIND");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_HAS_BIND = R.initMsg("技能已绑定", "SZ0099_MSG_COURSE_PROFESSION_REF_HAS_BIND", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_HAS_BIND");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_BIND_SUCCESS = R.initCode("240119", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_BIND_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_BIND_SUCCESS = R.initMsg("技能绑定成功", "SZ0099_MSG_COURSE_PROFESSION_REF_BIND_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_BIND_SUCCESS");

		//位置end
		
		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_FINDLIST_SUCCESS = R.initCode("240200", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_FINDLIST_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_FINDLIST_SUCCESS = R.initMsg("查询绑定列表成功", "SZ0099_MSG_COURSE_PROFESSION_REF_FINDLIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_FINDLIST_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_FINDLIST_EMPTY = R.initCode("240201", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_FINDLIST_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_FINDLIST_EMPTY = R.initMsg("绑定列表为空", "SZ0099_MSG_COURSE_PROFESSION_REF_FINDLIST_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_FINDLIST_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_BASEID_EMPTY = R.initCode("240202", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_BASEID_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_BASEID_EMPTY = R.initMsg("参数有误，baseId为空", "SZ0099_MSG_COURSE_PROFESSION_REF_BASEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_BASEID_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_EXTENDID_EMPTY = R.initCode("240203", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_EXTENDID_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_EXTENDID_EMPTY = R.initMsg("参数有误，extnedId为空", "SZ0099_MSG_COURSE_PROFESSION_REF_EXTENDID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_EXTENDID_EMPTY");
		
		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_POSITON_NOT_EXIST = R.initCode("240204", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_POSITON_NOT_EXIST");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_POSITON_NOT_EXIST = R.initMsg("技能已不存在", "SZ0099_MSG_COURSE_PROFESSION_REF_POSITON_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_POSITON_NOT_EXIST");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_POSITON_DELETED = R.initCode("240205", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_POSITON_DELETED");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_POSITON_DELETED = R.initMsg("技能已被删除", "SZ0099_MSG_COURSE_PROFESSION_REF_POSITON_DELETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_POSITON_DELETED");

		
		
		
		public static final String SZ0099_CODE_COURSE_PROFESSION_INVALID_ADAPTOR = R.initCode("240300", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_INVALID_ADAPTOR");
		public static final String SZ0099_MSG_COURSE_PROFESSION_INVALID_ADAPTOR = R.initMsg("不正确的适配器", "SZ0099_MSG_COURSE_PROFESSION_INVALID_ADAPTOR", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_INVALID_ADAPTOR");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_INVALID_HANDLER = R.initCode("240301", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_INVALID_HANDLER");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_INVALID_HANDLER = R.initMsg("不正确的关联处理器", "SZ0099_MSG_COURSE_PROFESSION_REF_INVALID_HANDLER", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_INVALID_HANDLER");

		
		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_VIEWTYPE_EMPTY = R.initCode("240302", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_VIEWTYPE_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_VIEWTYPE_EMPTY = R.initMsg("查看类型不能为空", "SZ0099_MSG_COURSE_PROFESSION_REF_VIEWTYPE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_VIEWTYPE_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_HAS_BINDED = R.initCode("240303", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_HAS_BINDED");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_HAS_BINDED = R.initMsg("已关联过了", "SZ0099_MSG_COURSE_PROFESSION_REF_HAS_BINDED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_HAS_BINDED");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_ID_EMPTY = R.initCode("240304", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_ID_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_ID_EMPTY = R.initMsg("删除关联时id不能为空", "SZ0099_MSG_COURSE_PROFESSION_REF_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_ID_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_MERGE_SUCCESS = R.initCode("240305", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_MERGE_SUCCESS");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_MERGE_SUCCESS = R.initMsg("关联修改成功", "SZ0099_MSG_COURSE_PROFESSION_REF_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_MERGE_SUCCESS");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_REMARK_EMPTY = R.initCode("240306", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_REMARK_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_REMARK_EMPTY = R.initMsg("备注不能为空", "SZ0099_MSG_COURSE_PROFESSION_REF_REMARK_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_REMARK_EMPTY");

		public static final String SZ0099_CODE_COURSE_PROFESSION_REF_TOPLEVEL_EMPTY = R.initCode("240307", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_TOPLEVEL_EMPTY");
		public static final String SZ0099_MSG_COURSE_PROFESSION_REF_TOPLEVEL_EMPTY = R.initMsg("置顶序号不能为空", "SZ0099_MSG_COURSE_PROFESSION_REF_TOPLEVEL_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PROFESSION_REF_TOPLEVEL_EMPTY");

	
	//---
	
}
