/**
 * Jit8j framework support by bruce yang 
 * contact email: 275060435@qq.com
 */
package dml.sz0099.course.app.module.define;

import org.jit4j.app.module.define.Jit4jRespCode;
import org.jit4j.app.module.define.R;

/**
 * <pre>
 * @formatter:off
 *
 * 课程响应码
 * @author bruce yang at 2018-09-04 09:01:29
 * 
 * ----------------------------------------------------------------------------------------
 * Requirement		Author		Date		Function
 * init				bruceyang	2018-09-04	basic init
 * 
 * @formatter:on
 * </pre>
 */

public class CourseRespCode extends Jit4jRespCode {

	// 引入开发者id
	public static final String COURSE_DEVELOPER_ID = CourseAppModule.APP_COURSE_ROOT.getDeveloperId();

	// 定义模块名, 课程系统模块
	public static final String MODULE_COURSE_ROOT = CourseAppModule.APP_COURSE_ROOT.getAd();

	public static final String SZ0099_CODE_COURSE_SYS_SUCCESS = R.initCode("100001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_SYS_SUCCESS");
	public static final String SZ0099_MSG_COURSE_SYS_SUCCESS = R.initMsg("课程操作成功", "SZ0099_MSG_COURSE_SYS_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_SYS_SUCCESS");


	
	public static final String SZ0099_CODE_COURSE_MEDIA_UPLOAD_SUCCESS = R.initCode("110001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_UPLOAD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_MEDIA_UPLOAD_SUCCESS = R.initMsg("文件上传成功", "SZ0099_MSG_COURSE_MEDIA_UPLOAD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_UPLOAD_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_DEVID_EMPTY = R.initCode("110002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_DEVID_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_DEVID_EMPTY = R.initMsg("开发者id不能为空", "SZ0099_MSG_COURSE_MEDIA_DEVID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_DEVID_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_POSITIONID_EMPTY = R.initCode("110003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_POSITIONID_EMPTY = R.initMsg("位置id不能为空", "SZ0099_MSG_COURSE_MEDIA_POSITIONID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_PROJECT_EMPTY = R.initCode("110004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_PROJECT_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_PROJECT_EMPTY = R.initMsg("project不能为空", "SZ0099_MSG_COURSE_MEDIA_PROJECT_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_PROJECT_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_MODULE_EMPTY = R.initCode("110005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_MODULE_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_MODULE_EMPTY = R.initMsg("module不能为空", "SZ0099_MSG_COURSE_MEDIA_MODULE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_MODULE_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_VARIETY_EMPTY = R.initCode("110006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_VARIETY_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_VARIETY_EMPTY = R.initMsg("variety不能为空", "SZ0099_MSG_COURSE_MEDIA_VARIETY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_VARIETY_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_POSITION_EMPTY = R.initCode("110007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITION_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_POSITION_EMPTY = R.initMsg("position不能为空", "SZ0099_MSG_COURSE_MEDIA_POSITION_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITION_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_POSITIONID_INVALID = R.initCode("110008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_INVALID");
	public static final String SZ0099_MSG_COURSE_MEDIA_POSITIONID_INVALID = R.initMsg("positionId不合法", "SZ0099_MSG_COURSE_MEDIA_POSITIONID_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_INVALID");

	public static final String SZ0099_CODE_COURSE_MEDIA_POSITIONID_DISABLED = R.initCode("110009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_DISABLED");
	public static final String SZ0099_MSG_COURSE_MEDIA_POSITIONID_DISABLED = R.initMsg("positionId已被禁用，请联系管理员", "SZ0099_MSG_COURSE_MEDIA_POSITIONID_DISABLED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_DISABLED");

	public static final String SZ0099_CODE_COURSE_MEDIA_POSITIONID_DELETED = R.initCode("110010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_DELETED");
	public static final String SZ0099_MSG_COURSE_MEDIA_POSITIONID_DELETED = R.initMsg("positionId已被删除，请联系管理员", "SZ0099_MSG_COURSE_MEDIA_POSITIONID_DELETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_POSITIONID_DELETED");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_USERID_EMPTY = R.initCode("110011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_USERID_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_USERID_EMPTY = R.initMsg("userId不能为空", "SZ0099_MSG_COURSE_MEDIA_USERID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_USERID_EMPTY");

	
	
	
	
	public static final String SZ0099_CODE_COURSE_MEDIA_MAINNUM_EXTRA = R.initCode("110012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_MAINNUM_EXTRA");
	public static final String SZ0099_MSG_COURSE_MEDIA_MAINNUM_EXTRA = R.initMsg("文件总数超限", "SZ0099_MSG_COURSE_MEDIA_MAINNUM_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_MAINNUM_EXTRA");

	public static final String SZ0099_CODE_COURSE_MEDIA_SUBNUM_EXTRA = R.initCode("110013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_SUBNUM_EXTRA");
	public static final String SZ0099_MSG_COURSE_MEDIA_SUBNUM_EXTRA = R.initMsg("该子类文件数超限", "SZ0099_MSG_COURSE_MEDIA_SUBNUM_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_SUBNUM_EXTRA");

	public static final String SZ0099_CODE_COURSE_MEDIA_SIZE_EXTRA = R.initCode("110014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_SIZE_EXTRA");
	public static final String SZ0099_MSG_COURSE_MEDIA_SIZE_EXTRA = R.initMsg("文件尺寸太大，请裁剪后上传", "SZ0099_MSG_COURSE_MEDIA_SIZE_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_SIZE_EXTRA");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_CREATE_FAIL = R.initCode("110015", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_CREATE_FAIL");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_EXTEND_CREATE_FAIL = R.initMsg("创建失败，请联系管理员！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_EXTEND_CREATE_FAIL", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_CREATE_FAIL");

	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_NOFILES = R.initCode("110016", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_NOFILES");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_EXTEND_NOFILES = R.initMsg("上传文件数为0，请重新选择！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_EXTEND_NOFILES", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_NOFILES");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_NOT_EXIST = R.initCode("110017", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_NOT_EXIST = R.initMsg("您要更新图片不存在！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_ID_EMPTY = R.initCode("110018", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_ID_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_ID_EMPTY = R.initMsg("ID不能为空！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_ID_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_NOT_LOGIN = R.initCode("110019", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_NOT_LOGIN = R.initMsg("用户尚未登录！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_MERGE_TITLE_SUCCESS = R.initCode("110020", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_MERGE_TITLE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_MERGE_TITLE_SUCCESS = R.initMsg("更新小标题成功！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_MERGE_TITLE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_MERGE_TITLE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_DELETE_SUCCESS = R.initCode("110021", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_DELETE_SUCCESS = R.initMsg("图片删除成功！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_REF_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_REF_DELETE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_NOT_EXIST = R.initCode("110022", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_MEDIA_IMAGE_EXTEND_NOT_EXIST = R.initMsg("Extend信息不存在！", "SZ0099_MSG_COURSE_MEDIA_IMAGE_EXTEND_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_IMAGE_EXTEND_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_MEDIA_MAINID_EMPTY = R.initCode("110023", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_MAINID_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_MAINID_EMPTY = R.initMsg("mainId不能为空", "SZ0099_MSG_COURSE_MEDIA_MAINID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_MAINID_EMPTY");

	public static final String SZ0099_CODE_COURSE_MEDIA_SUBID_EMPTY = R.initCode("110024", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_SUBID_EMPTY");
	public static final String SZ0099_MSG_COURSE_MEDIA_SUBID_EMPTY = R.initMsg("subId不能为空", "SZ0099_MSG_COURSE_MEDIA_SUBID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_MEDIA_SUBID_EMPTY");

	
	
	
	//----
	
	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_SAVE_SUCCESS = R.initCode("120000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_SAVE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_SAVE_SUCCESS = R.initMsg("项目类别保存成功", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_SAVE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_SAVE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_PERSIST_SUCCESS = R.initCode("120001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_PERSIST_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_PERSIST_SUCCESS = R.initMsg("项目类别创建成功", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_PERSIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_PERSIST_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_EXTRA = R.initCode("120002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_EXTRA");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_VARIETY_EXTRA = R.initMsg("品种数超限，请联系开发者", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_VARIETY_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_EXTRA");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_USER_NOT_LOGIN = R.initCode("120003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_USER_NOT_LOGIN = R.initMsg("还没登录，请登录后操作", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_EXIST = R.initCode("120004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_EXIST");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_VARIETY_EXIST = R.initMsg("项目品种已存在", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_VARIETY_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_EXIST");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_SELF = R.initCode("120005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_SELF");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_NOT_SELF = R.initMsg("无权编辑此项目品种", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_SELF");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_NOT_EXIST = R.initCode("120006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_VARIETY_NOT_EXIST = R.initMsg("项目品种不存在", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_VARIETY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_VARIETY_NOT_EXIST");

	
	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_HAS_CATEGORY = R.initCode("120007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_HAS_CATEGORY");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_HAS_CATEGORY = R.initMsg("项目品种下还有分类，不可删除", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_HAS_CATEGORY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_HAS_CATEGORY");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_DELETE_SUCCESS = R.initCode("120008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_DELETE_SUCCESS = R.initMsg("项目品种删除成功", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_DELETE_SUCCESS");

	
	//public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_SELF = R.initCode("120005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_SELF");
	//public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_NOT_SELF = R.initMsg("无权编辑此项目品种", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_SELF");

	
	public static final String SZ0099_CODE_COURSE_CATEGORY_ADD_SUCCESS = R.initCode("120106", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_ADD_SUCCESS = R.initMsg("分类添加成功", "SZ0099_MSG_COURSE_CATEGORY_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_EXIST = R.initCode("120107", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_CATEGORY_EXTEND_NOT_EXIST = R.initMsg("分类信息不存在", "SZ0099_MSG_COURSE_CATEGORY_EXTEND_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_EXTEND_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_CATEGORY_CODE_EXIST = R.initCode("120108", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_CODE_EXIST");
	public static final String SZ0099_MSG_COURSE_CATEGORY_CODE_EXIST = R.initMsg("分类code已存在", "SZ0099_MSG_COURSE_CATEGORY_CODE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_CODE_EXIST");

	public static final String SZ0099_CODE_COURSE_CATEGORY_MAINID_EMPTY = R.initCode("120109", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_MAINID_EMPTY");
	public static final String SZ0099_MSG_COURSE_CATEGORY_MAINID_EMPTY = R.initMsg("mainId不能为空", "SZ0099_MSG_COURSE_CATEGORY_MAINID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_MAINID_EMPTY");

	public static final String SZ0099_CODE_COURSE_CATEGORY_SUBID_EMPTY = R.initCode("120110", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_SUBID_EMPTY");
	public static final String SZ0099_MSG_COURSE_CATEGORY_SUBID_EMPTY = R.initMsg("subId不能为空", "SZ0099_MSG_COURSE_CATEGORY_SUBID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_SUBID_EMPTY");

	public static final String SZ0099_CODE_COURSE_CATEGORY_MERGE_SUCCESS = R.initCode("120111", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_MERGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_MERGE_SUCCESS = R.initMsg("分类保存成功", "SZ0099_MSG_COURSE_CATEGORY_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_MERGE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_NOT_EXIST = R.initCode("120112", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_CATEGORY_NOT_EXIST = R.initMsg("类别id不存在", "SZ0099_MSG_COURSE_CATEGORY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_CATEGORY_HAS_CHILDREN = R.initCode("120113", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_HAS_CHILDREN");
	public static final String SZ0099_MSG_COURSE_CATEGORY_HAS_CHILDREN = R.initMsg("该类别下面还有子类", "SZ0099_MSG_COURSE_CATEGORY_HAS_CHILDREN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_HAS_CHILDREN");

	public static final String SZ0099_CODE_COURSE_CATEGORY_DELETE_SUCCESS = R.initCode("120114", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_DELETE_SUCCESS = R.initMsg("类别删除成功", "SZ0099_MSG_COURSE_CATEGORY_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_DELETE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_HAS_REF = R.initCode("120115", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_HAS_REF");
	public static final String SZ0099_MSG_COURSE_CATEGORY_HAS_REF = R.initMsg("该类别下面关联有产品", "SZ0099_MSG_COURSE_CATEGORY_HAS_REF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_HAS_REF");

	public static final String SZ0099_CODE_COURSE_CATEGORY_DELETE_ALL_SUCCESS = R.initCode("120116", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_DELETE_ALL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_DELETE_ALL_SUCCESS = R.initMsg("已全部删除，成功", "SZ0099_MSG_COURSE_CATEGORY_DELETE_ALL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_DELETE_ALL_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_REFRESH_SUCCESS = R.initCode("120117", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_REFRESH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_REFRESH_SUCCESS = R.initMsg("分类刷新成功", "SZ0099_MSG_COURSE_CATEGORY_REFRESH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_REFRESH_SUCCESS");

	public static final String SZ0099_CODE_COURSE_CATEGORY_REF_HAS_BIND = R.initCode("120118", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_REF_HAS_BIND");
	public static final String SZ0099_MSG_COURSE_CATEGORY_REF_HAS_BIND = R.initMsg("类别已绑定", "SZ0099_MSG_COURSE_CATEGORY_REF_HAS_BIND", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_REF_HAS_BIND");

	public static final String SZ0099_CODE_COURSE_CATEGORY_REF_BIND_SUCCESS = R.initCode("120119", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_REF_BIND_SUCCESS");
	public static final String SZ0099_MSG_COURSE_CATEGORY_REF_BIND_SUCCESS = R.initMsg("类别绑定成功", "SZ0099_MSG_COURSE_CATEGORY_REF_BIND_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_CATEGORY_REF_BIND_SUCCESS");

	
	
	//位置begin
	public static final String SZ0099_CODE_COURSE_POSITION_MERGE_BIND_SUCCESS = R.initCode("131000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_MERGE_BIND_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_MERGE_BIND_SUCCESS = R.initMsg("位置绑定成功", "SZ0099_MSG_COURSE_POSITION_MERGE_BIND_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_MERGE_BIND_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_QUERY_LIST_SUCCESS = R.initCode("131001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_QUERY_LIST_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_QUERY_LIST_SUCCESS = R.initMsg("查询位置列表", "SZ0099_MSG_COURSE_POSITION_QUERY_LIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_QUERY_LIST_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_SAVE_SUCCESS = R.initCode("130000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_SAVE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_SAVE_SUCCESS = R.initMsg("项目位置保存成功", "SZ0099_MSG_COURSE_POSITION_EXTEND_SAVE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_SAVE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_PERSIST_SUCCESS = R.initCode("130001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_PERSIST_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_PERSIST_SUCCESS = R.initMsg("项目位置创建成功", "SZ0099_MSG_COURSE_POSITION_EXTEND_PERSIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_PERSIST_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_EXTRA = R.initCode("130002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_EXTRA");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_VARIETY_EXTRA = R.initMsg("品种数超限，请联系开发者", "SZ0099_MSG_COURSE_POSITION_EXTEND_VARIETY_EXTRA", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_EXTRA");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_USER_NOT_LOGIN = R.initCode("130003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_USER_NOT_LOGIN");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_USER_NOT_LOGIN = R.initMsg("还没登录，请登录后操作", "SZ0099_MSG_COURSE_POSITION_EXTEND_USER_NOT_LOGIN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_USER_NOT_LOGIN");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_EXIST = R.initCode("130004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_EXIST");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_VARIETY_EXIST = R.initMsg("项目品种已存在", "SZ0099_MSG_COURSE_POSITION_EXTEND_VARIETY_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_EXIST");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_SELF = R.initCode("130005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_SELF");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_NOT_SELF = R.initMsg("无权编辑此项目品种", "SZ0099_MSG_COURSE_POSITION_EXTEND_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_SELF");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_NOT_EXIST = R.initCode("130006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_VARIETY_NOT_EXIST = R.initMsg("项目品种不存在", "SZ0099_MSG_COURSE_POSITION_EXTEND_VARIETY_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_VARIETY_NOT_EXIST");

	
	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_HAS_POSITION = R.initCode("130007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_HAS_POSITION");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_HAS_POSITION = R.initMsg("项目品种下还有位置，不可删除", "SZ0099_MSG_COURSE_POSITION_EXTEND_HAS_POSITION", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_HAS_POSITION");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_DELETE_SUCCESS = R.initCode("130008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_DELETE_SUCCESS = R.initMsg("项目品种删除成功", "SZ0099_MSG_COURSE_POSITION_EXTEND_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_DELETE_SUCCESS");

	
	//public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_SELF = R.initCode("130005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_SELF");
	//public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_NOT_SELF = R.initMsg("无权编辑此项目品种", "SZ0099_MSG_COURSE_POSITION_EXTEND_NOT_SELF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_SELF");

	
	public static final String SZ0099_CODE_COURSE_POSITION_ADD_SUCCESS = R.initCode("130106", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_ADD_SUCCESS = R.initMsg("位置添加成功", "SZ0099_MSG_COURSE_POSITION_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_EXIST = R.initCode("130107", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_POSITION_EXTEND_NOT_EXIST = R.initMsg("位置信息不存在", "SZ0099_MSG_COURSE_POSITION_EXTEND_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_EXTEND_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_POSITION_CODE_EXIST = R.initCode("130108", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_CODE_EXIST");
	public static final String SZ0099_MSG_COURSE_POSITION_CODE_EXIST = R.initMsg("位置code已存在", "SZ0099_MSG_COURSE_POSITION_CODE_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_CODE_EXIST");

	public static final String SZ0099_CODE_COURSE_POSITION_MAINID_EMPTY = R.initCode("130109", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_MAINID_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_MAINID_EMPTY = R.initMsg("mainId不能为空", "SZ0099_MSG_COURSE_POSITION_MAINID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_MAINID_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_SUBID_EMPTY = R.initCode("130110", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_SUBID_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_SUBID_EMPTY = R.initMsg("subId不能为空", "SZ0099_MSG_COURSE_POSITION_SUBID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_SUBID_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_MERGE_SUCCESS = R.initCode("130111", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_MERGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_MERGE_SUCCESS = R.initMsg("位置保存成功", "SZ0099_MSG_COURSE_POSITION_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_MERGE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_NOT_EXIST = R.initCode("130112", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_POSITION_NOT_EXIST = R.initMsg("位置id不存在", "SZ0099_MSG_COURSE_POSITION_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_POSITION_HAS_CHILDREN = R.initCode("130113", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_HAS_CHILDREN");
	public static final String SZ0099_MSG_COURSE_POSITION_HAS_CHILDREN = R.initMsg("该位置下面还有子类", "SZ0099_MSG_COURSE_POSITION_HAS_CHILDREN", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_HAS_CHILDREN");

	public static final String SZ0099_CODE_COURSE_POSITION_DELETE_SUCCESS = R.initCode("130114", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_DELETE_SUCCESS = R.initMsg("位置删除成功", "SZ0099_MSG_COURSE_POSITION_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_DELETE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_HAS_REF = R.initCode("130115", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_HAS_REF");
	public static final String SZ0099_MSG_COURSE_POSITION_HAS_REF = R.initMsg("该位置下面关联有产品", "SZ0099_MSG_COURSE_POSITION_HAS_REF", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_HAS_REF");

	public static final String SZ0099_CODE_COURSE_POSITION_DELETE_ALL_SUCCESS = R.initCode("130116", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_DELETE_ALL_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_DELETE_ALL_SUCCESS = R.initMsg("已全部删除，成功", "SZ0099_MSG_COURSE_POSITION_DELETE_ALL_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_DELETE_ALL_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_REFRESH_SUCCESS = R.initCode("130117", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REFRESH_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_REFRESH_SUCCESS = R.initMsg("位置刷新成功", "SZ0099_MSG_COURSE_POSITION_REFRESH_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REFRESH_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_HAS_BIND = R.initCode("130118", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_HAS_BIND");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_HAS_BIND = R.initMsg("位置已绑定", "SZ0099_MSG_COURSE_POSITION_REF_HAS_BIND", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_HAS_BIND");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_BIND_SUCCESS = R.initCode("130119", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_BIND_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_BIND_SUCCESS = R.initMsg("位置绑定成功", "SZ0099_MSG_COURSE_POSITION_REF_BIND_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_BIND_SUCCESS");

	//位置end
	
	public static final String SZ0099_CODE_COURSE_POSITION_REF_FINDLIST_SUCCESS = R.initCode("130200", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_FINDLIST_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_FINDLIST_SUCCESS = R.initMsg("查询绑定列表成功", "SZ0099_MSG_COURSE_POSITION_REF_FINDLIST_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_FINDLIST_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_FINDLIST_EMPTY = R.initCode("130201", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_FINDLIST_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_FINDLIST_EMPTY = R.initMsg("绑定列表为空", "SZ0099_MSG_COURSE_POSITION_REF_FINDLIST_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_FINDLIST_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_BASEID_EMPTY = R.initCode("130202", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_BASEID_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_BASEID_EMPTY = R.initMsg("参数有误，baseId为空", "SZ0099_MSG_COURSE_POSITION_REF_BASEID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_BASEID_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_EXTENDID_EMPTY = R.initCode("130203", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_EXTENDID_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_EXTENDID_EMPTY = R.initMsg("参数有误，extnedId为空", "SZ0099_MSG_COURSE_POSITION_REF_EXTENDID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_EXTENDID_EMPTY");
	
	public static final String SZ0099_CODE_COURSE_POSITION_REF_POSITON_NOT_EXIST = R.initCode("130204", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_POSITON_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_POSITON_NOT_EXIST = R.initMsg("位置已不存在", "SZ0099_MSG_COURSE_POSITION_REF_POSITON_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_POSITON_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_POSITON_DELETED = R.initCode("130205", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_POSITON_DELETED");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_POSITON_DELETED = R.initMsg("位置已被删除", "SZ0099_MSG_COURSE_POSITION_REF_POSITON_DELETED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_POSITON_DELETED");

	
	
	
	public static final String SZ0099_CODE_COURSE_POSITION_INVALID_ADAPTOR = R.initCode("130300", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_INVALID_ADAPTOR");
	public static final String SZ0099_MSG_COURSE_POSITION_INVALID_ADAPTOR = R.initMsg("不正确的位置适配器", "SZ0099_MSG_COURSE_POSITION_INVALID_ADAPTOR", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_INVALID_ADAPTOR");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_INVALID_HANDLER = R.initCode("130301", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_INVALID_HANDLER");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_INVALID_HANDLER = R.initMsg("不正确的位置关联处理器", "SZ0099_MSG_COURSE_POSITION_REF_INVALID_HANDLER", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_INVALID_HANDLER");

	
	public static final String SZ0099_CODE_COURSE_POSITION_REF_VIEWTYPE_EMPTY = R.initCode("130302", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_VIEWTYPE_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_VIEWTYPE_EMPTY = R.initMsg("查看类型不能为空", "SZ0099_MSG_COURSE_POSITION_REF_VIEWTYPE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_VIEWTYPE_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_HAS_BINDED = R.initCode("130303", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_HAS_BINDED");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_HAS_BINDED = R.initMsg("已关联过了", "SZ0099_MSG_COURSE_POSITION_REF_HAS_BINDED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_HAS_BINDED");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_ID_EMPTY = R.initCode("130304", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_ID_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_ID_EMPTY = R.initMsg("删除关联时id不能为空", "SZ0099_MSG_COURSE_POSITION_REF_ID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_ID_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_MERGE_SUCCESS = R.initCode("130305", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_MERGE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_MERGE_SUCCESS = R.initMsg("关联修改成功", "SZ0099_MSG_COURSE_POSITION_REF_MERGE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_MERGE_SUCCESS");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_REMARK_EMPTY = R.initCode("130306", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_REMARK_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_REMARK_EMPTY = R.initMsg("备注不能为空", "SZ0099_MSG_COURSE_POSITION_REF_REMARK_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_REMARK_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_TOPLEVEL_EMPTY = R.initCode("130307", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_TOPLEVEL_EMPTY");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_TOPLEVEL_EMPTY = R.initMsg("置顶序号不能为空", "SZ0099_MSG_COURSE_POSITION_REF_TOPLEVEL_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_TOPLEVEL_EMPTY");

	public static final String SZ0099_CODE_COURSE_POSITION_REF_SYNC_SUCCESS = R.initCode("130308", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_SYNC_SUCCESS");
	public static final String SZ0099_MSG_COURSE_POSITION_REF_SYNC_SUCCESS = R.initMsg("关联信息同步成功", "SZ0099_MSG_COURSE_POSITION_REF_SYNC_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_POSITION_REF_SYNC_SUCCESS");

	
	
	public static final String SZ0099_CODE_COURSE_USER_EMAIL_EXISTS = R.initCode("312000", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_EXISTS");
	public static final String SZ0099_MSG_COURSE_USER_EMAIL_EXISTS = R.initMsg("Email已存在", "SZ0099_MSG_COURSE_USER_EMAIL_EXISTS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_EXISTS");

	public static final String SZ0099_CODE_COURSE_USER_EMAIL_MODIFY_SUCCESS = R.initCode("312001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_EMAIL_MODIFY_SUCCESS = R.initMsg("Email修改成功", "SZ0099_MSG_COURSE_USER_EMAIL_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_EMAIL_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_MOBILE_MODIFY_SUCCESS = R.initCode("312002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_MOBILE_MODIFY_SUCCESS = R.initMsg("手机号修改成功", "SZ0099_MSG_COURSE_USER_MOBILE_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_EMPTY = R.initCode("312003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_EMPTY = R.initMsg("身份证号码不能为空", "SZ0099_MSG_COURSE_USER_IDENTITY_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EMPTY");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_INVALID = R.initCode("312004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_INVALID");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_INVALID = R.initMsg("身份证号码不合法！", "SZ0099_MSG_COURSE_USER_IDENTITY_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_INVALID");

	public static final String SZ0099_CODE_COURSE_USERID_EMPTY = R.initCode("312005", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USERID_EMPTY");
	public static final String SZ0099_MSG_COURSE_USERID_EMPTY = R.initMsg("用户未登录，请登录后重试！", "SZ0099_MSG_COURSE_USERID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USERID_EMPTY");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_VERIFY_SUCCESS = R.initCode("312006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_VERIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_VERIFY_SUCCESS = R.initMsg("用户身份证认证提交成功，请奈心等待工作人员认证审核", "SZ0099_MSG_COURSE_USER_IDENTITY_VERIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_VERIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_NOT_EXIST = R.initCode("312006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NOT_EXIST");
	public static final String SZ0099_MSG_COURSE_USER_NOT_EXIST = R.initMsg("用户不存在", "SZ0099_MSG_COURSE_USER_NOT_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NOT_EXIST");

	public static final String SZ0099_CODE_COURSE_USER_ID_INVALID = R.initCode("312007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_ID_INVALID");
	public static final String SZ0099_MSG_COURSE_USER_ID_INVALID = R.initMsg("用户ID不合法", "SZ0099_MSG_COURSE_USER_ID_INVALID", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_ID_INVALID");

	public static final String SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_INPROCESS = R.initCode("312008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_INPROCESS");
	public static final String SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_INPROCESS= R.initMsg("已在审核中", "SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_INPROCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_INPROCESS");

	public static final String SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_PASSED = R.initCode("312009", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_PASSED");
	public static final String SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_PASSED= R.initMsg("已在审核通过", "SZ0099_MSG_COURSE_USER_IDVERIFY_HAS_PASSED", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_HAS_PASSED");

	public static final String SZ0099_CODE_COURSE_USER_IDVERIFY_FACE_EMPTY = R.initCode("312010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_FACE_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_IDVERIFY_FACE_EMPTY= R.initMsg("身份证照片未上传", "SZ0099_MSG_COURSE_USER_IDVERIFY_FACE_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDVERIFY_FACE_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_USER_NICKNAME_EMPTY = R.initCode("312011", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_USER_NICKNAME_EMPTY= R.initMsg("昵称不能为空", "SZ0099_MSG_COURSE_USER_NICKNAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_EMPTY");

	public static final String SZ0099_CODE_COURSE_USER_NICKNAME_MODIFY_SUCCESS = R.initCode("312012", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_MODIFY_SUCCESS");
	public static final String SZ0099_MSG_COURSE_USER_NICKNAME_MODIFY_SUCCESS = R.initMsg("昵称修改成功", "SZ0099_MSG_COURSE_USER_NICKNAME_MODIFY_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_NICKNAME_MODIFY_SUCCESS");

	public static final String SZ0099_CODE_COURSE_USER_IDENTITY_EXISTS = R.initCode("312013", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EXISTS");
	public static final String SZ0099_MSG_COURSE_USER_IDENTITY_EXISTS = R.initMsg("身份证号码已存在", "SZ0099_MSG_COURSE_USER_IDENTITY_EXISTS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_IDENTITY_EXISTS");

	public static final String SZ0099_CODE_COURSE_USER_MOBILE_EXISTS = R.initCode("312014", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_EXISTS");
	public static final String SZ0099_MSG_COURSE_USER_MOBILE_EXISTS = R.initMsg("手机号码已存在", "SZ0099_MSG_COURSE_USER_MOBILE_EXISTS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_USER_MOBILE_EXISTS");

	
	
	public static final String SZ0099_CODE_COURSE_TAG_ADD_SUCCESS = R.initCode("311001", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ADD_SUCCESS");
	public static final String SZ0099_MSG_COURSE_TAG_ADD_SUCCESS = R.initMsg("标签添加成功", "SZ0099_MSG_COURSE_TAG_ADD_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_ADD_SUCCESS");

	public static final String SZ0099_CODE_COURSE_TAG_EMPTY = R.initCode("311002", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_EMPTY = R.initMsg("标签不能为空", "SZ0099_MSG_COURSE_TAG_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_NAME_EMPTY = R.initCode("311003", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NAME_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAG_NAME_EMPTY = R.initMsg("标签名称不能为空", "SZ0099_MSG_COURSE_TAG_NAME_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NAME_EMPTY");

	
	public static final String SZ0099_CODE_COURSE_ARTICLE_TAG_EXIST = R.initCode("311004", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_TAG_EXIST");
	public static final String SZ0099_MSG_COURSE_ARTICLE_TAG_EXIST = R.initMsg("文章标签已存在", "SZ0099_MSG_COURSE_ARTICLE_TAG_EXIST", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_ARTICLE_TAG_EXIST");

	
	public static final String SZ0099_CODE_COURSE_PTAGID_EMPTY = R.initCode("311006", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PTAGID_EMPTY");
	public static final String SZ0099_MSG_COURSE_PTAGID_EMPTY = R.initMsg("删除标签时，ID不能为空", "SZ0099_MSG_COURSE_PTAGID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_PTAGID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAGID_EMPTY = R.initCode("311007", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAGID_EMPTY");
	public static final String SZ0099_MSG_COURSE_TAGID_EMPTY = R.initMsg("删除标签时，标签ID不能为空", "SZ0099_MSG_COURSE_TAGID_EMPTY", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAGID_EMPTY");

	public static final String SZ0099_CODE_COURSE_TAG_DELETE_SUCCESS = R.initCode("311008", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_SUCCESS");
	public static final String SZ0099_MSG_COURSE_TAG_DELETE_SUCCESS = R.initMsg("标签删除成功", "SZ0099_MSG_COURSE_TAG_DELETE_SUCCESS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_DELETE_SUCCESS");

	
	public static final String SZ0099_CODE_COURSE_TAG_NUM_EXTRS = R.initCode("311010", MODULE_COURSE_ROOT, COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NUM_EXTRS");
	public static final String SZ0099_MSG_COURSE_TAG_NUM_EXTRS = R.initMsg("标签数量已超限", "SZ0099_MSG_COURSE_TAG_NUM_EXTRS", COURSE_DEVELOPER_ID, "SZ0099_CODE_COURSE_TAG_NUM_EXTRS");

}
